# Generated by Django 5.1.7 on 2025-06-04 23:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DossierMedical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "groupe_sanguin",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                        null=True,
                        verbose_name="Groupe sanguin",
                    ),
                ),
                (
                    "poids",
                    models.FloatField(blank=True, null=True, verbose_name="Poids (kg)"),
                ),
                (
                    "taille",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Taille (cm)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dossiers_crees",
                        to="rh.personnel",
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossier Médical",
                "verbose_name_plural": "Dossiers Médicaux",
            },
        ),
        migrations.CreateModel(
            name="Antecedent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_antecedent",
                    models.CharField(
                        choices=[
                            ("MEDICAL", "Antécédent Médical"),
                            ("CHIRURGICAL", "Antécédent Chirurgical"),
                            ("FAMILIAL", "Antécédent Familial"),
                            ("ALLERGIE", "Allergie"),
                            ("TRAITEMENT", "Traitement en cours"),
                        ],
                        max_length=20,
                        verbose_name="Type d'antécédent",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description détaillée")),
                (
                    "date_decouverte",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de découverte"
                    ),
                ),
                (
                    "gravite",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LEGERE", "Légère"),
                            ("MODEREE", "Modérée"),
                            ("SEVERE", "Sévère"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Gravité",
                    ),
                ),
                (
                    "commentaire_medecin",
                    models.TextField(
                        blank=True, null=True, verbose_name="Commentaire du médecin"
                    ),
                ),
                (
                    "documents",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="antecedents/",
                        verbose_name="Documents associés",
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="antecedents",
                        to="patients.dossiermedical",
                        verbose_name="Dossier associé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Antécédent Médical",
                "verbose_name_plural": "Antécédents Médicaux",
                "ordering": ["-date_decouverte"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "place_of_birth",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Lieu de naissance",
                    ),
                ),
                (
                    "social_security_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        unique=True,
                        verbose_name="Numéro de sécurité sociale",
                    ),
                ),
                (
                    "nom_de_assure",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nom de l'assuré",
                    ),
                ),
                (
                    "securite_sociale",
                    models.CharField(
                        blank=True,
                        choices=[("1", "CNAS"), ("2", "CASNOS")],
                        max_length=1,
                        null=True,
                        verbose_name="Sécurité sociale",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")],
                        max_length=1,
                        verbose_name="Genre",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Adresse"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Créé le",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "id_created_par",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_par",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="patients_id_created_par",
                        to="rh.personnel",
                    ),
                ),
                (
                    "id_updated_par",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_updated_par",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="patients_id_updated_par",
                        to="rh.personnel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
            },
        ),
        migrations.AddField(
            model_name="dossiermedical",
            name="patient",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dossier_medical",
                to="patients.patient",
                verbose_name="Patient associé",
            ),
        ),
    ]
