# Generated by Django 5.1.7 on 2025-04-17 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
        ("rh", "0003_rename_id_decharge_par_planning_decharge_id_created_par"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="id_created_par",
            field=models.ForeignKey(
                blank=True,
                db_column="created_par",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="patients_id_created_par",
                to="rh.personnel",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="id_updated_par",
            field=models.ForeignKey(
                blank=True,
                db_column="id_updated_par",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="patients_id_updated_par",
                to="rh.personnel",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AddField(
            model_name="patient",
            name="nome_de_assure",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nom de l'assuré"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="place_of_birth",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Lieu de naissance"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="social_security_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                unique=True,
                verbose_name="Numéro de sécurité sociale",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="sucurite_sociale",
            field=models.CharField(
                blank=True,
                choices=[("1", "CNAS"), ("2", "CASNOS")],
                max_length=1,
                null=True,
                verbose_name="Sécurité sociale",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Adresse"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de naissance"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[("M", "Masculin"), ("F", "Féminin")],
                max_length=1,
                verbose_name="Genre",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Téléphone"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
