# Generated by Django 5.1.7 on 2025-08-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_import_patients"),
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="patient",
            name="patients_pa_is_acti_54ba9f_idx",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="is_active",
            new_name="est_active",
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["est_active"], name="patients_pa_est_act_6078f8_idx"
            ),
        ),
    ]
