# Generated by Django 5.1.7 on 2025-04-17 19:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patient_id_created_par_patient_id_updated_par_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="nome_de_assure",
            new_name="nom_de_assure",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="sucurite_sociale",
            new_name="securite_sociale",
        ),
        migrations.AlterField(
            model_name="patient",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Créé le",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
                verbose_name="Mis à jour le",
            ),
            preserve_default=False,
        ),
    ]
