# Generated by Django 5.1.7 on 2025-04-30 21:43

import accueil.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nom du groupe"),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Classe CSS de l'icône (ex: fas fa-home)",
                        max_length=255,
                        verbose_name="Icône",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Ordre")),
                (
                    "permission",
                    models.CharField(
                        blank=True,
                        help_text="Format: app_label.permission_codename",
                        max_length=255,
                        null=True,
                        verbose_name="Permission requise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Groupe de menu",
                "verbose_name_plural": "Groupes de menus",
                "ordering": ["order"],
            },
            bases=(models.Model, accueil.models.PermissionMixin),
        ),
        migrations.CreateModel(
            name="ConfigDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("page", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        help_text="Nom de la vue ou URL",
                        max_length=255,
                        verbose_name="Route",
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="Libellé")),
                ("icon", models.CharField(max_length=255, verbose_name="Icône")),
                (
                    "permission",
                    models.CharField(
                        blank=True,
                        help_text="Format: app_label.permission_codename",
                        max_length=255,
                        null=True,
                        verbose_name="Permission requise",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Ordre")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="accueil.menugroup",
                        verbose_name="Groupe parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Élément de menu",
                "verbose_name_plural": "Éléments de menu",
                "ordering": ["order"],
            },
            bases=(models.Model, accueil.models.PermissionMixin),
        ),
        migrations.CreateModel(
            name="NavbarItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("title", "Titre"), ("link", "Lien")],
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="Libellé")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Classe Font Awesome (ex: fas fa-home)",
                        max_length=50,
                        null=True,
                        verbose_name="Icône",
                    ),
                ),
                (
                    "url_name",
                    models.CharField(max_length=255, verbose_name="Nom de la vue"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Ordre")),
                (
                    "permission",
                    models.CharField(
                        blank=True,
                        help_text="Format: app_label.permission_codename",
                        max_length=255,
                        null=True,
                        verbose_name="Permission requise",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="navbar_items",
                        to="accueil.menuitem",
                        verbose_name="Élément associé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Élément de navigation",
                "verbose_name_plural": "Éléments de navigation",
                "ordering": ["order"],
            },
            bases=(models.Model, accueil.models.PermissionMixin),
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("light", "Clair"), ("dark", "Sombre")],
                        default="light",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
