# Generated by Django 5.1.7 on 2025-04-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=255)),
                ("icon", models.CharField(max_length=255)),
                ("privilege", models.CharField(blank=True, max_length=255, null=True)),
                ("badge", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "menu_items",
                "managed": True,
            },
        ),
    ]
