# Generated by Django 5.1.7 on 2025-04-21 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("icon", models.CharField(max_length=255)),
                ("order", models.IntegerField(default=0)),
                (
                    "permission",
                    models.CharField(
                        blank=True,
                        help_text="Format: app_label.permission_codename",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ConfigDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("page", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "config_date",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MenuItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=255)),
                ("icon", models.CharField(max_length=255)),
                (
                    "permission",
                    models.CharField(
                        blank=True,
                        help_text="Format: app_label.permission_codename",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("n", models.IntegerField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="accueil.menugroup",
                    ),
                ),
            ],
            options={
                "db_table": "menu_items",
                "permissions": (
                    ("view_menu_items_helpdesk", "Peut voir le  helpdesk"),
                    ("view_menu_items_dashboard", "Peut voir le Dashboard"),
                    ("view_menu_items_plannings", "Peut voir le  plannings"),
                    ("view_menu_items_documents", "Peut voir le  documents"),
                ),
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("light", "Clair"), ("dark", "Sombre")],
                        default="light",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
