# Generated by Django 5.1.7 on 2025-04-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accueil", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitems",
            name="n",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
