# Generated by Django 5.1.7 on 2025-04-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0002_menuitems_n'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitems',
            name='privilege',
        ),
        migrations.AddField(
            model_name='menuitems',
            name='permission',
            field=models.CharField(blank=True, help_text='Format: app_label.permission_codename', max_length=255, null=True),
        ),
    ]
