# Generated by Django 5.1.7 on 2025-04-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accueil", "0003_remove_menuitems_privilege_menuitems_permission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitems",
            options={"managed": True, "verbose_name": "MenuItems Ticket"},
        ),
    ]
