# Generated by Django 5.1.7 on 2025-04-02 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accueil", "0004_alter_menuitems_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitems",
            options={"managed": True},
        ),
    ]
