# Generated by Django 5.1.7 on 2025-04-02 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accueil", "0005_alter_menuitems_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitems",
            options={
                "managed": True,
                "permissions": (
                    (
                        "view_menu_items_helpdesk",
                        "Peut voir les éléments du menu helpdesk",
                    ),
                ),
            },
        ),
    ]
