# Generated by Django 5.1.7 on 2025-04-03 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accueil", "0007_alter_menuitems_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitems",
            name="badge",
        ),
    ]
