# Generated by Django 5.1.7 on 2025-04-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accueil", "0009_configdate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitems",
            options={
                "managed": True,
                "permissions": (
                    (
                        "view_menu_items_helpdesk",
                        "Peut voir les éléments du menu helpdesk",
                    ),
                    ("view_menu_items_dashboard", "Peut voir le Dashboard dashboard"),
                    (
                        "view_menu_items_plannings",
                        "Peut voir les éléments du menu plannings",
                    ),
                ),
            },
        ),
    ]
