# Generated by Django 5.1.7 on 2025-04-09 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accueil", "0010_alter_menuitems_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitems",
            options={
                "managed": True,
                "permissions": (
                    ("view_menu_items_helpdesk", "Peut voir le  helpdesk"),
                    ("view_menu_items_dashboard", "Peut voir le Dashboard"),
                    ("view_menu_items_plannings", "Peut voir le  plannings"),
                    ("view_menu_items_documents", "Peut voir le  documents"),
                ),
            },
        ),
    ]
