# Generated by Django 5.1.7 on 2025-04-09 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_auto_20250408_1631"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documents",
            options={
                "permissions": (
                    ("view_document", "Peut visualiser le document"),
                    ("download_document", "Peut télécharger le document"),
                )
            },
        ),
    ]
