# Generated by Django 5.1.7 on 2025-04-30 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medical", "0001_initial"),
        ("patients", "0001_initial"),
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "code_produit",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Code produit"
                    ),
                ),
                (
                    "code_barres",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Code-barres",
                    ),
                ),
                (
                    "type_produit",
                    models.CharField(
                        choices=[("MED", "Médicament"), ("CONS", "Consommable")],
                        max_length=4,
                        verbose_name="Type de produit",
                    ),
                ),
                (
                    "prix_achat",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix d'achat"
                    ),
                ),
                (
                    "prix_vente",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix de vente"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Produit",
                "verbose_name_plural": "Produits",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Consommation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite_consomme",
                    models.PositiveIntegerField(verbose_name="Quantité consommée"),
                ),
                (
                    "date_consommation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de consommation"
                    ),
                ),
                (
                    "prix_unitaire_vente",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Prix unitaire au moment de la vente",
                    ),
                ),
                (
                    "acte_associe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="medical.prestationacte",
                        verbose_name="Acte associé",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="patients.patient",
                        verbose_name="Patient",
                    ),
                ),
                (
                    "prestation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="medical.prestation",
                        verbose_name="Prestation",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rh.personnel",
                        verbose_name="Personnel responsable",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="medical.service",
                        verbose_name="Service utilisateur",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacies.produit",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consommation",
                "verbose_name_plural": "Consommations",
            },
        ),
        migrations.CreateModel(
            name="Achat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fournisseur",
                    models.CharField(max_length=255, verbose_name="Fournisseur"),
                ),
                (
                    "quantite_achetee",
                    models.PositiveIntegerField(verbose_name="Quantité achetée"),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix unitaire"
                    ),
                ),
                (
                    "date_achat",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'achat"
                    ),
                ),
                (
                    "numero_lot",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Numéro de lot",
                    ),
                ),
                (
                    "date_peremption",
                    models.DateField(verbose_name="Date de péremption"),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacies.produit",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Achat",
                "verbose_name_plural": "Achats",
            },
        ),
        migrations.CreateModel(
            name="Transfert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite_transferee",
                    models.PositiveIntegerField(verbose_name="Quantité transférée"),
                ),
                (
                    "date_transfert",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de transfert"
                    ),
                ),
                (
                    "date_peremption",
                    models.DateField(verbose_name="Date de péremption"),
                ),
                (
                    "numero_lot",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Numéro de lot",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacies.produit",
                        verbose_name="Produit",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rh.personnel",
                        verbose_name="Responsable du transfert",
                    ),
                ),
                (
                    "service_destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferts_entrants",
                        to="medical.service",
                        verbose_name="Service de destination",
                    ),
                ),
                (
                    "service_origine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferts_sortants",
                        to="medical.service",
                        verbose_name="Service d'origine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfert",
                "verbose_name_plural": "Transferts",
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField(verbose_name="Quantité")),
                (
                    "date_peremption",
                    models.DateField(verbose_name="Date de péremption"),
                ),
                (
                    "numero_lot",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Numéro de lot",
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacies.produit",
                        verbose_name="Produit",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="medical.service",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock",
                "verbose_name_plural": "Stocks",
                "unique_together": {
                    ("produit", "service", "date_peremption", "numero_lot")
                },
            },
        ),
    ]
