# Generated by Django 5.1.7 on 2025-07-09 23:09

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("medical", "0001_initial"),
        ("rh", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BonLivraisonInterne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_livraison", models.DateTimeField(auto_now_add=True)),
                (
                    "numero_bl",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numéro BL interne"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bon de livraison interne",
                "verbose_name_plural": "Bons de livraison interne",
            },
        ),
        migrations.CreateModel(
            name="CategorieProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                (
                    "marge_beneficiaire_defaut",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        help_text="Marge bénéficiaire par défaut en %",
                        max_digits=5,
                    ),
                ),
                (
                    "tva_applicable",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("19.00"),
                        help_text="Taux TVA applicable en %",
                        max_digits=5,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pharmacies.categorieproduit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie produit",
                "verbose_name_plural": "Catégories produits",
            },
        ),
        migrations.CreateModel(
            name="DemandeInterne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField()),
                ("date_demande", models.DateTimeField(auto_now_add=True)),
                ("date_besoin", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("EN_ATTENTE", "En attente"),
                            ("APPROUVE", "Approuvé"),
                            ("REFUSE", "Refusé"),
                            ("LIVRE", "Livre"),
                        ],
                        default="BROUILLON",
                        max_length=20,
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                (
                    "service_demandeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandes_internes",
                        to="medical.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande interne",
                "verbose_name_plural": "Demandes internes",
            },
        ),
        migrations.CreateModel(
            name="BonCommandeInterne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "numero_commande",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numéro de commande"
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rh.personnel",
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "demande",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commande_interne",
                        to="pharmacies.demandeinterne",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bon de commande interne",
                "verbose_name_plural": "Bons de commande interne",
            },
        ),
        migrations.CreateModel(
            name="ExpressionBesoin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(default=uuid.uuid4, max_length=50, unique=True),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("VALIDE", "Validée"),
                            ("REJETE", "Rejetée"),
                            ("SERVIE", "Servie"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                (
                    "service_approvisionneur",
                    models.ForeignKey(
                        limit_choices_to={"est_pharmacies": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="besoins_recus",
                        to="medical.service",
                    ),
                ),
                (
                    "service_demandeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="besoins_emmis",
                        to="medical.service",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="besoins_valides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expression de besoin",
                "verbose_name_plural": "Expressions de besoin",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_fournisseur",
                    models.CharField(
                        help_text="Identifiant unique du fournisseur",
                        max_length=20,
                        unique=True,
                        verbose_name="Code unique",
                    ),
                ),
                (
                    "raison_sociale",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Raison sociale"
                    ),
                ),
                (
                    "forme_juridique",
                    models.CharField(
                        choices=[
                            ("SARL", "SARL"),
                            ("EURL", "EURL"),
                            ("SNC", "SNC"),
                            ("ETS", "ETS"),
                            ("AUTRE", "Autre"),
                        ],
                        default="SARL",
                        max_length=50,
                    ),
                ),
                (
                    "domaine_activite",
                    models.CharField(max_length=100, verbose_name="Domaine d'activité"),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telephone", models.CharField(max_length=20)),
                ("adresse", models.TextField()),
                ("ville", models.CharField(max_length=100)),
                ("pays", models.CharField(default="Algérie", max_length=100)),
                (
                    "conditions_paiement",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(365),
                        ],
                        verbose_name="Délai de paiement (jours)",
                    ),
                ),
                (
                    "limite_credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "solde",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Solde actuel",
                    ),
                ),
                (
                    "mode_paiement_prefere",
                    models.CharField(
                        choices=[
                            ("VIREMENT", "Virement bancaire"),
                            ("CHEQUE", "Chèque"),
                            ("ESPECES", "Espèces"),
                            ("CREDIT", "Crédit"),
                        ],
                        default="VIREMENT",
                        max_length=50,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ACTIF", "Actif"),
                            ("SUSPENDU", "Suspendu"),
                            ("ARCHIVE", "Archivé"),
                        ],
                        default="ACTIF",
                        max_length=50,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fournisseur",
                "verbose_name_plural": "Fournisseurs",
                "ordering": ["-date_creation"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code_fournisseur", "raison_sociale"),
                        name="unique_fournisseur",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CommandeFournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(default=uuid.uuid4, max_length=50, unique=True),
                ),
                ("date_commande", models.DateTimeField(auto_now_add=True)),
                ("date_confirmation", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("EN_ATTENTE", "En attente"),
                            ("CONFIRME", "Confirmée"),
                            ("ANNULE", "Annulée"),
                            ("LIVREE", "Livrée"),
                        ],
                        default="BROUILLON",
                        max_length=20,
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commandes_validees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "besoin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commandes",
                        to="pharmacies.expressionbesoin",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacies.fournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commande fournisseur",
                "verbose_name_plural": "Commandes fournisseurs",
                "ordering": ["-date_commande"],
            },
        ),
        migrations.CreateModel(
            name="Livraison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(default=uuid.uuid4, max_length=50, unique=True),
                ),
                ("date_livraison_prevue", models.DateField()),
                ("date_reception", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_TRANSIT", "En transit"),
                            ("RECU", "Reçu"),
                            ("PARTIEL", "Reçu partiellement"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="EN_TRANSIT",
                        max_length=20,
                    ),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="livraisons",
                        to="pharmacies.commandefournisseur",
                    ),
                ),
                (
                    "recepteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="livraisons_recues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Livraison",
                "verbose_name_plural": "Livraisons",
                "ordering": ["-date_livraison_prevue"],
            },
        ),
        migrations.CreateModel(
            name="BonReception",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(default=uuid.uuid4, max_length=50, unique=True),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "controleur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bons_reception",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "livraison",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bon_reception",
                        to="pharmacies.livraison",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bon de réception",
                "verbose_name_plural": "Bons de réception",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=255, verbose_name="Nom du produit"),
                ),
                (
                    "code_produit",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Code produit"
                    ),
                ),
                (
                    "code_barres",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "type_produit",
                    models.CharField(
                        choices=[
                            ("MED", "Médicament"),
                            ("CONS", "Consommable"),
                            ("DISP", "Dispositif médical"),
                            ("REAC", "Réactif"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "prix_achat",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "prix_vente",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("est_actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Produit",
                "verbose_name_plural": "Produits",
                "ordering": ["nom"],
                "indexes": [
                    models.Index(
                        fields=["code_produit"], name="pharmacies__code_pr_0958ff_idx"
                    ),
                    models.Index(
                        fields=["type_produit"], name="pharmacies__type_pr_aaa996_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="demandeinterne",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="pharmacies.produit"
            ),
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.IntegerField(verbose_name="Quantité")),
                (
                    "date_peremption",
                    models.DateField(verbose_name="Date de péremption"),
                ),
                (
                    "numero_lot",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Numéro de lot",
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacies.produit",
                        verbose_name="Produit",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="medical.service",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock",
                "verbose_name_plural": "Stocks",
            },
        ),
        migrations.CreateModel(
            name="AjustementStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite_avant", models.IntegerField()),
                ("quantite_apres", models.IntegerField()),
                (
                    "motif",
                    models.CharField(
                        choices=[
                            ("ERREUR", "Erreur de saisie"),
                            ("DOMMAGE", "Produit endommagé"),
                            ("PERDU", "Produit perdu"),
                            ("INVENTAIRE", "Ajustement inventaire"),
                        ],
                        max_length=15,
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                ("date_ajustement", models.DateTimeField(auto_now_add=True)),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="rh.personnel"
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacies.stock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transfert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite_transferee",
                    models.PositiveIntegerField(verbose_name="Quantité transférée"),
                ),
                (
                    "numero_lot",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Numéro de lot",
                    ),
                ),
                (
                    "date_peremption",
                    models.DateField(verbose_name="Date de péremption"),
                ),
                (
                    "date_transfert",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de transfert"
                    ),
                ),
                (
                    "date_reception",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de réception"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_TRANSIT", "En transit"),
                            ("LIVRE", "Livré"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="EN_TRANSIT",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, null=True, verbose_name="Commentaire"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacies.produit",
                        verbose_name="Produit",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rh.personnel",
                        verbose_name="Responsable du transfert",
                    ),
                ),
                (
                    "service_destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferts_entrants",
                        to="medical.service",
                        verbose_name="Service de destination",
                    ),
                ),
                (
                    "service_origine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferts_sortants",
                        to="medical.service",
                        verbose_name="Service d'origine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfert",
                "verbose_name_plural": "Transferts",
                "db_table": "pharmacies_transfert",
                "ordering": ["-date_transfert"],
            },
        ),
        migrations.CreateModel(
            name="MouvementStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[
                            ("ENTREE", "Entrée de stock"),
                            ("SORTIE", "Sortie de stock"),
                            ("TRANSFERT_ENTREE", "Transfert (entrée)"),
                            ("TRANSFERT_SORTIE", "Transfert (sortie)"),
                            ("AJUSTEMENT", "Ajustement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantite", models.IntegerField()),
                (
                    "lot_concerne",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("date_mouvement", models.DateTimeField(auto_now_add=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="medical.service",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacies.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de stock",
                "verbose_name_plural": "Mouvements de stock",
                "indexes": [
                    models.Index(
                        fields=["type_mouvement"], name="pharmacies__type_mo_981624_idx"
                    ),
                    models.Index(
                        fields=["date_mouvement"], name="pharmacies__date_mo_cd72b8_idx"
                    ),
                    models.Index(
                        fields=["produit"], name="pharmacies__produit_fac560_idx"
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="pharmacies__content_2b1c21_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LigneLivraison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite_livree", models.PositiveIntegerField()),
                ("numero_lot", models.CharField(max_length=50)),
                ("date_peremption", models.DateField()),
                (
                    "livraison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="pharmacies.livraison",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacies.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de livraison",
                "verbose_name_plural": "Lignes de livraison",
                "unique_together": {("livraison", "produit", "numero_lot")},
            },
        ),
        migrations.CreateModel(
            name="LigneCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite_commandee", models.PositiveIntegerField()),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="pharmacies.commandefournisseur",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacies.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de commande",
                "verbose_name_plural": "Lignes de commande",
                "unique_together": {("commande", "produit")},
            },
        ),
        migrations.CreateModel(
            name="LigneBesoin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite_demandee", models.PositiveIntegerField()),
                (
                    "quantite_validee",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "besoin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="pharmacies.expressionbesoin",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacies.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de besoin",
                "verbose_name_plural": "Lignes de besoin",
                "unique_together": {("besoin", "produit")},
            },
        ),
        migrations.CreateModel(
            name="ConsommationProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite_defaut", models.PositiveIntegerField()),
                ("quantite_reelle", models.PositiveIntegerField()),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "montant_solde",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("date_consommation", models.DateTimeField(auto_now_add=True)),
                (
                    "prestation_acte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consommations",
                        to="medical.prestationacte",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacies.produit",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["prestation_acte"],
                        name="pharmacies__prestat_df1013_idx",
                    ),
                    models.Index(
                        fields=["produit"], name="pharmacies__produit_abf8a5_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["date_peremption"], name="pharmacies__date_pe_19d79f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["numero_lot"], name="pharmacies__numero__28b6af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transfert",
            index=models.Index(
                fields=["service_origine", "statut"],
                name="pharmacies__service_78ddf5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transfert",
            index=models.Index(
                fields=["service_destination", "statut"],
                name="pharmacies__service_977afb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transfert",
            index=models.Index(
                fields=["produit", "date_transfert"],
                name="pharmacies__produit_c015a6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transfert",
            index=models.Index(
                fields=["statut", "date_transfert"],
                name="pharmacies__statut_8516f0_idx",
            ),
        ),
    ]
