# Generated by Django 5.1.7 on 2025-08-26 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produit",
            old_name="est_actif",
            new_name="est_active",
        ),
    ]
