# Generated by Django 5.1.7 on 2025-06-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0001_initial"),
    ]

    operations = []
