# Generated by Django 5.1.7 on 2025-07-12 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0003_service_est_actif"),
        ("pharmacies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expressionbesoin",
            name="priorite",
            field=models.CharField(
                choices=[
                    ("NORMALE", "Normale"),
                    ("URGENTE", "Urgente"),
                    ("CRITIQUE", "Critique"),
                ],
                default="NORMALE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="expressionbesoin",
            name="type_approvisionnement",
            field=models.CharField(
                choices=[
                    ("EXTERNE", "Approvisionnement externe (fournisseur)"),
                    ("INTERNE", "Approvisionnement interne (pharmacie)"),
                ],
                default="EXTERNE",
                help_text="Type d'approvisionnement demandé",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="expressionbesoin",
            name="service_approvisionneur",
            field=models.ForeignKey(
                help_text="Service qui traite la demande (pharmacie pour externe, pharmacie pour interne)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="besoins_recus",
                to="medical.service",
            ),
        ),
    ]
