# Generated by Django 5.1.7 on 2025-05-01 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0003_acteproduit"),
        ("pharmacies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsommationProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite_defaut", models.PositiveIntegerField()),
                ("quantite_reelle", models.PositiveIntegerField()),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
                ("montant_solde", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_consommation", models.DateTimeField(auto_now_add=True)),
                (
                    "prestation_acte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consommations",
                        to="medical.prestationacte",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacies.produit",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["prestation_acte"],
                        name="pharmacies__prestat_df1013_idx",
                    ),
                    models.Index(
                        fields=["produit"], name="pharmacies__produit_abf8a5_idx"
                    ),
                ],
            },
        ),
    ]
