# Generated by Django 5.1.7 on 2025-06-08 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0002_auto_20250605_1346"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produit",
            name="nom_commercial",
        ),
    ]
