# Generated by Django 5.1.7 on 2025-07-12 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0002_expressionbesoin_priorite_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boncommandeinterne",
            name="demande",
        ),
        migrations.RemoveField(
            model_name="boncommandeinterne",
            name="responsable",
        ),
        migrations.DeleteModel(
            name="BonLivraisonInterne",
        ),
        migrations.RemoveField(
            model_name="demandeinterne",
            name="produit",
        ),
        migrations.RemoveField(
            model_name="demandeinterne",
            name="service_demandeur",
        ),
        migrations.RemoveField(
            model_name="transfert",
            name="produit",
        ),
        migrations.RemoveField(
            model_name="transfert",
            name="responsable",
        ),
        migrations.RemoveField(
            model_name="transfert",
            name="service_destination",
        ),
        migrations.RemoveField(
            model_name="transfert",
            name="service_origine",
        ),
        migrations.DeleteModel(
            name="BonCommandeInterne",
        ),
        migrations.DeleteModel(
            name="DemandeInterne",
        ),
        migrations.DeleteModel(
            name="Transfert",
        ),
    ]
