# Generated by Django 5.1.7 on 2025-05-03 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0002_consommationproduit"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Consommation",
        ),
    ]
