# Generated by Django 5.1.7 on 2025-07-12 04:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0003_service_est_actif"),
        ("pharmacies", "0003_remove_boncommandeinterne_demande_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="commandefournisseur",
            name="besoin",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type_approvisionnement": "EXTERNE"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commandes",
                to="pharmacies.expressionbesoin",
            ),
        ),
        migrations.CreateModel(
            name="DemandeInterne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(default=uuid.uuid4, max_length=50, unique=True),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                ("date_preparation", models.DateTimeField(blank=True, null=True)),
                ("date_livraison", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("VALIDEE", "Validée"),
                            ("PREPAREE", "Préparée"),
                            ("LIVREE", "Livrée"),
                            ("REJETEE", "Rejetée"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                (
                    "besoin",
                    models.OneToOneField(
                        limit_choices_to={"type_approvisionnement": "INTERNE"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demande_interne",
                        to="pharmacies.expressionbesoin",
                    ),
                ),
                (
                    "livree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demandes_internes_livrees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "preparee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demandes_internes_preparees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandes_recues",
                        to="medical.service",
                    ),
                ),
                (
                    "validee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demandes_internes_validees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande interne",
                "verbose_name_plural": "Demandes internes",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="LigneDemandeInterne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite_demandee", models.PositiveIntegerField()),
                (
                    "quantite_accordee",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("observations", models.TextField(blank=True)),
                (
                    "demande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="pharmacies.demandeinterne",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacies.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de demande interne",
                "verbose_name_plural": "Lignes de demande interne",
                "unique_together": {("demande", "produit")},
            },
        ),
    ]
