# Generated by Django 5.1.7 on 2025-05-04 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("medical", "0004_service_est_stockeur"),
        ("pharmacies", "0003_delete_consommation"),
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AjustementStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite_avant", models.IntegerField()),
                ("quantite_apres", models.IntegerField()),
                (
                    "motif",
                    models.CharField(
                        choices=[
                            ("ERREUR", "Erreur de saisie"),
                            ("DOMMAGE", "Produit endommagé"),
                            ("PERDU", "Produit perdu"),
                            ("INVENTAIRE", "Ajustement inventaire"),
                        ],
                        max_length=15,
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                ("date_ajustement", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MouvementStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[
                            ("ENTREE", "Entrée de stock"),
                            ("SORTIE", "Sortie de stock"),
                            ("TRANSFERT_ENTREE", "Transfert (entrée)"),
                            ("TRANSFERT_SORTIE", "Transfert (sortie)"),
                            ("AJUSTEMENT", "Ajustement"),
                        ],
                        max_length=17,
                    ),
                ),
                ("quantite", models.IntegerField()),
                (
                    "lot_concerne",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("date_mouvement", models.DateTimeField(auto_now_add=True)),
                ("object_id", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Mouvement de stock",
                "verbose_name_plural": "Mouvements de stock",
            },
        ),
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="achat",
            name="service_destination",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="medical.service",
                verbose_name="Service destinataire",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="produit",
            index=models.Index(
                fields=["code_produit"], name="pharmacies__code_pr_0958ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="produit",
            index=models.Index(
                fields=["type_produit"], name="pharmacies__type_pr_aaa996_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["date_peremption"], name="pharmacies__date_pe_19d79f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["numero_lot"], name="pharmacies__numero__28b6af_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.UniqueConstraint(
                fields=("produit", "service", "date_peremption", "numero_lot"),
                name="unique_stock_entry",
            ),
        ),
        migrations.AddField(
            model_name="ajustementstock",
            name="responsable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="rh.personnel"
            ),
        ),
        migrations.AddField(
            model_name="ajustementstock",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="pharmacies.stock"
            ),
        ),
        migrations.AddField(
            model_name="mouvementstock",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="mouvementstock",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="pharmacies.produit"
            ),
        ),
        migrations.AddField(
            model_name="mouvementstock",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="medical.service"
            ),
        ),
        migrations.AddIndex(
            model_name="mouvementstock",
            index=models.Index(
                fields=["type_mouvement"], name="pharmacies__type_mo_981624_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mouvementstock",
            index=models.Index(
                fields=["date_mouvement"], name="pharmacies__date_mo_cd72b8_idx"
            ),
        ),
    ]
