# Generated by Django 5.1.7 on 2025-05-04 12:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0004_ajustementstock_mouvementstock_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_fournisseur",
                    models.CharField(
                        help_text="Identifiant unique du fournisseur",
                        max_length=20,
                        unique=True,
                        verbose_name="Code unique",
                    ),
                ),
                (
                    "raison_sociale",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Raison sociale"
                    ),
                ),
                (
                    "forme_juridique",
                    models.CharField(
                        choices=[
                            ("SARL", "SARL"),
                            ("SA", "SA"),
                            ("SNC", "SNC"),
                            ("EI", "Entreprise individuelle"),
                            ("AUTRE", "Autre"),
                        ],
                        default="SARL",
                        max_length=50,
                    ),
                ),
                (
                    "domaine_activite",
                    models.CharField(max_length=100, verbose_name="Domaine d'activité"),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telephone", models.CharField(max_length=20)),
                ("adresse", models.TextField()),
                ("ville", models.CharField(max_length=100)),
                ("pays", models.CharField(default="Algérie", max_length=100)),
                (
                    "conditions_paiement",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(365),
                        ],
                        verbose_name="Délai de paiement (jours)",
                    ),
                ),
                (
                    "limite_credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "solde",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Solde actuel",
                    ),
                ),
                (
                    "mode_paiement_prefere",
                    models.CharField(
                        choices=[
                            ("VIREMENT", "Virement bancaire"),
                            ("CHEQUE", "Chèque"),
                            ("ESPECES", "Espèces"),
                            ("CREDIT", "Crédit"),
                        ],
                        default="VIREMENT",
                        max_length=50,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ACTIF", "Actif"),
                            ("SUSPENDU", "Suspendu"),
                            ("ARCHIVE", "Archivé"),
                        ],
                        default="ACTIF",
                        max_length=50,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fournisseur",
                "verbose_name_plural": "Fournisseurs",
                "ordering": ["-date_creation"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code_fournisseur", "raison_sociale"),
                        name="unique_fournisseur",
                    )
                ],
            },
        ),
        migrations.AlterField(
            model_name="achat",
            name="fournisseur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="pharmacies.fournisseur",
                verbose_name="Fournisseur",
            ),
        ),
        migrations.CreateModel(
            name="HistoriquePaiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_paiement",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("VIREMENT", "Virement bancaire"),
                            ("CHEQUE", "Chèque"),
                            ("ESPECES", "Espèces"),
                            ("CREDIT", "Crédit"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence transaction"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("COMPLETE", "Complété"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="EN_ATTENTE",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "achat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pharmacies.achat",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique_paiements",
                        to="pharmacies.fournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de paiement",
                "verbose_name_plural": "Historiques de paiement",
                "ordering": ["-date_paiement"],
            },
        ),
    ]
