# Generated by Django 5.1.7 on 2025-07-12 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0005_alter_expressionbesoin_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expressionbesoin",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expressions_besoin_creees",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bonreception",
            name="livraison",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bon_reception",
                to="pharmacies.livraison",
            ),
        ),
        migrations.AlterField(
            model_name="demandeinterne",
            name="besoin",
            field=models.OneToOneField(
                limit_choices_to={"type_approvisionnement": "INTERNE"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="demande_interne",
                to="pharmacies.expressionbesoin",
            ),
        ),
        migrations.AlterField(
            model_name="lignebesoin",
            name="besoin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lignes",
                to="pharmacies.expressionbesoin",
            ),
        ),
        migrations.AlterField(
            model_name="lignecommande",
            name="commande",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lignes",
                to="pharmacies.commandefournisseur",
            ),
        ),
        migrations.AlterField(
            model_name="lignedemandeinterne",
            name="demande",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lignes",
                to="pharmacies.demandeinterne",
            ),
        ),
        migrations.AlterField(
            model_name="lignelivraison",
            name="livraison",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lignes",
                to="pharmacies.livraison",
            ),
        ),
    ]
