# Generated by Django 5.1.7 on 2025-05-05 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0004_service_est_stockeur"),
        ("pharmacies", "0005_fournisseur_alter_achat_fournisseur_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fournisseur",
            name="forme_juridique",
            field=models.CharField(
                choices=[
                    ("SARL", "SARL"),
                    ("EURL", "EURL"),
                    ("SNC", "SNC"),
                    ("ETS", "ETS"),
                    ("AUTRE", "Autre"),
                ],
                default="SARL",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="BonCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_commande",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numéro de commande"
                    ),
                ),
                ("date_commande", models.DateField(auto_now_add=True)),
                ("date_livraison_prevue", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("VALIDE", "Validé"),
                            ("LIVRE", "Livré"),
                            ("FACTURE", "Facturé"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="BROUILLON",
                        max_length=20,
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commandes",
                        to="pharmacies.fournisseur",
                    ),
                ),
                (
                    "service_destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="medical.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bon de commande",
                "verbose_name_plural": "Bons de commande",
                "ordering": ["-date_commande"],
            },
        ),
        migrations.CreateModel(
            name="BonLivraison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_bl", models.CharField(max_length=50, unique=True)),
                ("date_livraison", models.DateField(auto_now_add=True)),
                (
                    "fichier_bl",
                    models.FileField(blank=True, null=True, upload_to="bl/"),
                ),
                ("est_complet", models.BooleanField(default=False)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="livraisons",
                        to="pharmacies.boncommande",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LigneCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField()),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_peremption", models.DateField()),
                ("numero_lot", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="pharmacies.boncommande",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacies.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de commande",
                "verbose_name_plural": "Lignes de commande",
            },
        ),
        migrations.CreateModel(
            name="OrdrePaiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=50, unique=True)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("VIREMENT", "Virement bancaire"),
                            ("CHEQUE", "Chèque"),
                            ("ESPECES", "Espèces"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_paiement", models.DateField()),
                (
                    "preuve",
                    models.FileField(blank=True, null=True, upload_to="paiements/"),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paiements",
                        to="pharmacies.boncommande",
                    ),
                ),
            ],
        ),
    ]
