# Generated by Django 5.1.7 on 2025-05-05 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0004_service_est_stockeur"),
        ("pharmacies", "0006_alter_fournisseur_forme_juridique_boncommande_and_more"),
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BonCommandeInterne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "numero_commande",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numéro de commande"
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rh.personnel",
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bon de commande interne",
                "verbose_name_plural": "Bons de commande interne",
            },
        ),
        migrations.AddField(
            model_name="transfert",
            name="commande_interne",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transferts",
                to="pharmacies.boncommandeinterne",
            ),
        ),
        migrations.CreateModel(
            name="BonLivraisonInterne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_livraison", models.DateTimeField(auto_now_add=True)),
                (
                    "numero_bl",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numéro BL interne"
                    ),
                ),
                (
                    "transfert",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="livraison_interne",
                        to="pharmacies.transfert",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bon de livraison interne",
                "verbose_name_plural": "Bons de livraison interne",
            },
        ),
        migrations.CreateModel(
            name="DemandeInterne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField()),
                ("date_demande", models.DateTimeField(auto_now_add=True)),
                ("date_besoin", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("EN_ATTENTE", "En attente"),
                            ("APPROUVE", "Approuvé"),
                            ("REFUSE", "Refusé"),
                            ("LIVRE", "Livre"),
                        ],
                        default="BROUILLON",
                        max_length=20,
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacies.produit",
                    ),
                ),
                (
                    "service_demandeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandes_internes",
                        to="medical.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande interne",
                "verbose_name_plural": "Demandes internes",
            },
        ),
        migrations.AddField(
            model_name="boncommandeinterne",
            name="demande",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commande_interne",
                to="pharmacies.demandeinterne",
            ),
        ),
    ]
