# Generated by Django 5.1.7 on 2025-05-06 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0007_boncommandeinterne_transfert_commande_interne_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achat",
            name="date_peremption",
            field=models.DateTimeField(verbose_name="Date de péremption"),
        ),
        migrations.AlterField(
            model_name="boncommande",
            name="date_commande",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="boncommande",
            name="date_livraison_prevue",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="boncommande",
            name="numero_commande",
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="bonlivraison",
            name="date_livraison",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="lignecommande",
            name="date_peremption",
            field=models.DateTimeField(),
        ),
    ]
