# Generated by Django 5.1.7 on 2025-05-06 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0008_alter_achat_date_peremption_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bonlivraison",
            options={
                "ordering": ["-date_livraison"],
                "verbose_name": "Bon de livraison",
                "verbose_name_plural": "Bons de livraison",
            },
        ),
        migrations.AddField(
            model_name="achat",
            name="livraison",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="achats",
                to="pharmacies.bonlivraison",
            ),
        ),
        migrations.AddField(
            model_name="bonlivraison",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="bonlivraison",
            name="commande",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="livraisons",
                to="pharmacies.boncommande",
                verbose_name="Commande associée",
            ),
        ),
        migrations.AlterField(
            model_name="bonlivraison",
            name="date_livraison",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de livraison"
            ),
        ),
        migrations.AlterField(
            model_name="bonlivraison",
            name="est_complet",
            field=models.BooleanField(default=False, verbose_name="Livraison complète"),
        ),
        migrations.AlterField(
            model_name="bonlivraison",
            name="fichier_bl",
            field=models.FileField(
                blank=True, upload_to="bl/%Y/%m/%d/", verbose_name="Fichier BL"
            ),
        ),
        migrations.AlterField(
            model_name="bonlivraison",
            name="numero_bl",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Numéro BL"
            ),
        ),
    ]
