# Generated by Django 5.1.7 on 2025-05-06 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0009_alter_bonlivraison_options_achat_livraison_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stock",
            name="unique_stock_entry",
        ),
    ]
