# Generated by Django 5.1.7 on 2025-06-18 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0004_remove_produit_pharmacies__est_act_6b1822_idx_and_more"),
        ("pharmacies", "0010_remove_stock_unique_stock_entry"),
    ]

    operations = []
