# Generated by Django 5.1.7 on 2025-06-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0011_merge_20250618_1228"),
    ]

    operations = [

    ]
