# Generated by Django 5.1.7 on 2025-06-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0012_produit_est_actif"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="est_actif",
            field=models.BooleanField(default=True),
        ),
    ]
