# Generated by Django 5.1.7 on 2025-06-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0013_produit_est_actif"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bonlivraison",
            name="created_by",
        ),
    ]
