# Generated by Django 5.1.7 on 2025-06-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0015_bonlivraison_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lignecommande",
            name="quantite",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
