# Generated by Django 5.1.7 on 2025-06-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0016_alter_lignecommande_quantite"),
    ]

    operations = [
        migrations.AddField(
            model_name="boncommande",
            name="fichier_commande",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="commandes/%Y/%m/",
                verbose_name="Fichier PDF",
            ),
        ),
        migrations.AlterField(
            model_name="boncommande",
            name="statut",
            field=models.CharField(
                choices=[
                    ("BROUILLON", "Brouillon"),
                    ("VALIDE", "Validé"),
                    ("LIVRE", "Livré"),
                    ("ANNULE", "Annulé"),
                ],
                default="BROUILLON",
                max_length=20,
            ),
        ),
    ]
