# Generated by Django 5.1.7 on 2025-06-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0017_boncommande_fichier_commande_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boncommande",
            name="fichier_commande",
        ),
        migrations.AlterField(
            model_name="boncommande",
            name="statut",
            field=models.CharField(
                choices=[
                    ("BROUILLON", "Brouillon"),
                    ("VALIDE", "Validé"),
                    ("LIVRE", "Livré"),
                    ("FACTURE", "Facturé"),
                    ("ANNULE", "Annulé"),
                ],
                default="BROUILLON",
                max_length=20,
            ),
        ),
    ]
