# Generated by Django 5.1.7 on 2025-06-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("medical", "0004_service_est_stockeur"),
        ("pharmacies", "0018_remove_boncommande_fichier_commande_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consommationproduit",
            name="montant_solde",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mouvementstock",
            name="type_mouvement",
            field=models.CharField(
                choices=[
                    ("ENTREE", "Entrée de stock"),
                    ("SORTIE", "Sortie de stock"),
                    ("TRANSFERT_ENTREE", "Transfert (entrée)"),
                    ("TRANSFERT_SORTIE", "Transfert (sortie)"),
                    ("AJUSTEMENT", "Ajustement"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="mouvementstock",
            index=models.Index(
                fields=["produit"], name="pharmacies__produit_fac560_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mouvementstock",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="pharmacies__content_2b1c21_idx",
            ),
        ),
    ]
