# Generated by Django 5.1.7 on 2025-06-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0019_alter_consommationproduit_montant_solde_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bonlivraisoninterne",
            name="transfert",
        ),
        migrations.AlterField(
            model_name="stock",
            name="quantite",
            field=models.IntegerField(verbose_name="Quantité"),
        ),
        migrations.DeleteModel(
            name="Transfert",
        ),
    ]
