# Generated by Django 5.1.7 on 2025-04-21 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medecin", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                ("id_service", models.AutoField(primary_key=True, serialize=False)),
                ("service_name", models.CharField(max_length=255)),
                ("color", models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                "db_table": "services",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RendezVous",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_heure",
                    models.DateTimeField(verbose_name="Date et heure du rendez-vous"),
                ),
                (
                    "duree",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Durée prévue (minutes)"
                    ),
                ),
                ("motif", models.TextField(verbose_name="Motif de consultation")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PLANIFIE", "Planifié"),
                            ("CONFIRME", "Confirmé"),
                            ("ANNULE", "Annulé"),
                            ("TERMINE", "Terminé"),
                        ],
                        default="PLANIFIE",
                        max_length=20,
                        verbose_name="Statut du rendez-vous",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notes supplémentaires"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rendez_vous_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "medecin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rendez_vous",
                        to="medecin.medecin",
                        verbose_name="Médecin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rendez-vous Médical",
                "verbose_name_plural": "Rendez-vous Médicaux",
                "ordering": ["-date_heure"],
            },
        ),
    ]
