# Generated by Django 5.1.7 on 2025-08-09 00:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Acte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("libelle", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Acte",
                "verbose_name_plural": "Actes",
            },
        ),
        migrations.CreateModel(
            name="Prestation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_prestation",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de réalisation",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PLANIFIE", "Planifié"),
                            ("REALISE", "Réalisé"),
                            ("PAYE", "Payé"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="PLANIFIE",
                        max_length=25,
                        verbose_name="Statut de la prestation",
                    ),
                ),
                (
                    "prix_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Coût total"
                    ),
                ),
                (
                    "prix_supplementaire",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Coût supplémentaire pour la prestation (hors actes et consommations)",
                        max_digits=10,
                        verbose_name="Frais supplémentaires",
                    ),
                ),
                (
                    "prix_supplementaire_medecin",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Part médecin du supplément",
                    ),
                ),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="Observations médicales"),
                ),
                (
                    "stock_impact_applied",
                    models.BooleanField(
                        default=False, verbose_name="Impact stock appliqué"
                    ),
                ),
            ],
            options={
                "verbose_name": "Prestation médicale",
                "verbose_name_plural": "Prestations médicales",
                "ordering": ["-date_prestation"],
            },
        ),
        migrations.CreateModel(
            name="PrestationActe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tarif_conventionne",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Tarif conventionné",
                    ),
                ),
                (
                    "convention_accordee",
                    models.BooleanField(
                        blank=True,
                        help_text="Uniquement si une convention est sélectionnée",
                        null=True,
                        verbose_name="Statut Convention",
                    ),
                ),
                (
                    "honoraire_medecin",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(
                                Decimal("99999999.99")
                            ),
                        ],
                        verbose_name="Honoraire médecin",
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire médical"),
                ),
            ],
            options={
                "verbose_name": "Détail d'acte",
                "verbose_name_plural": "Détails des actes",
            },
        ),
        migrations.CreateModel(
            name="PrestationAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "champ",
                    models.CharField(max_length=100, verbose_name="Champ modifié"),
                ),
                (
                    "ancienne_valeur",
                    models.TextField(
                        blank=True, null=True, verbose_name="Valeur avant modification"
                    ),
                ),
                (
                    "nouvelle_valeur",
                    models.TextField(
                        blank=True, null=True, verbose_name="Valeur après modification"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit de prestation",
                "verbose_name_plural": "Audits de prestations",
                "ordering": ["-date_modification"],
            },
        ),
        migrations.CreateModel(
            name="RendezVous",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_heure",
                    models.DateTimeField(verbose_name="Date et heure du rendez-vous"),
                ),
                (
                    "duree",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Durée prévue (minutes)"
                    ),
                ),
                ("motif", models.TextField(verbose_name="Motif de consultation")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PLANIFIE", "Planifié"),
                            ("CONFIRME", "Confirmé"),
                            ("ANNULE", "Annulé"),
                            ("TERMINE", "Terminé"),
                        ],
                        default="PLANIFIE",
                        max_length=20,
                        verbose_name="Statut du rendez-vous",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notes supplémentaires"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rendez-vous Médical",
                "verbose_name_plural": "Rendez-vous Médicaux",
                "ordering": ["-date_heure"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("color", models.CharField(blank=True, max_length=7, null=True)),
                ("est_stockeur", models.BooleanField(default=False)),
                ("est_pharmacies", models.BooleanField(default=False)),
                (
                    "est_hospitalier",
                    models.BooleanField(
                        default=False, verbose_name="Service hospitalier"
                    ),
                ),
                ("est_actif", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ActeProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite_defaut",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Quantité par défaut"
                    ),
                ),
                (
                    "acte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produits_defaut",
                        to="medical.acte",
                        verbose_name="Acte médical",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit par défaut pour acte",
                "verbose_name_plural": "Produits par défaut pour actes",
            },
        ),
    ]
