# Generated by Django 5.1.7 on 2025-04-22 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medecin", "0002_initial"),
        ("medical", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="prestation",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prestations",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AddField(
            model_name="prestationacte",
            name="acte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prestations_liees",
                to="medical.acte",
            ),
        ),
        migrations.AddField(
            model_name="prestationacte",
            name="prestation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actes_details",
                to="medical.prestation",
            ),
        ),
        migrations.AddField(
            model_name="prestation",
            name="actes",
            field=models.ManyToManyField(
                related_name="prestations",
                through="medical.PrestationActe",
                to="medical.acte",
                verbose_name="Actes médicaux",
            ),
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rendez_vous_crees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="medecin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rendez_vous",
                to="medecin.medecin",
                verbose_name="Médecin",
            ),
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rendez_vous",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="medical.service",
            ),
        ),
        migrations.AddField(
            model_name="acte",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actes",
                to="medical.service",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="prestationacte",
            unique_together={("prestation", "acte")},
        ),
        migrations.AddIndex(
            model_name="prestation",
            index=models.Index(
                fields=["date_prestation"], name="medical_pre_date_pr_25cb1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prestation",
            index=models.Index(fields=["statut"], name="medical_pre_statut_32b6cc_idx"),
        ),
        migrations.AddIndex(
            model_name="prestation",
            index=models.Index(
                fields=["patient"], name="medical_pre_patient_154bca_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rendezvous",
            constraint=models.UniqueConstraint(
                fields=("medecin", "date_heure"), name="unique_booking_per_doctor"
            ),
        ),
    ]
