# Generated by Django 5.1.7 on 2025-08-19 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medecin", "0002_initial"),
        ("medical", "0001_initial"),
        ("patients", "0001_initial"),
        ("pharmacies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="acteproduit",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="pharmacies.produit",
                verbose_name="Produit associé",
            ),
        ),
        migrations.AddField(
            model_name="acteproduitinclus",
            name="acte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produits_inclus",
                to="medical.actelocation",
                verbose_name="Acte",
            ),
        ),
        migrations.AddField(
            model_name="acteproduitinclus",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pharmacies.produit",
                verbose_name="Produit inclus",
            ),
        ),
        migrations.AddField(
            model_name="blocproduitinclus",
            name="bloc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produits_inclus",
                to="medical.bloc",
                verbose_name="Bloc",
            ),
        ),
        migrations.AddField(
            model_name="blocproduitinclus",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pharmacies.produit",
                verbose_name="Produit inclus",
            ),
        ),
        migrations.AddField(
            model_name="consommationproduitbloc",
            name="produit",
            field=models.ForeignKey(
                help_text="Produit consommé",
                on_delete=django.db.models.deletion.CASCADE,
                to="pharmacies.produit",
            ),
        ),
        migrations.AddField(
            model_name="forfaitacteinclus",
            name="acte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forfaits_incluant",
                to="medical.actelocation",
                verbose_name="Acte inclus",
            ),
        ),
        migrations.AddField(
            model_name="forfaitacteinclus",
            name="forfait",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actes_inclus",
                to="medical.forfait",
                verbose_name="Forfait",
            ),
        ),
        migrations.AddField(
            model_name="forfaitproduitinclus",
            name="forfait",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produits",
                to="medical.forfait",
                verbose_name="Forfait associé",
            ),
        ),
        migrations.AddField(
            model_name="forfaitproduitinclus",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forfaits",
                to="pharmacies.produit",
                verbose_name="Produit associé",
            ),
        ),
        migrations.AddField(
            model_name="honorairesmedecin",
            name="acte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="honoraires_medecins",
                to="medical.actekt",
                verbose_name="ActeKt médical",
            ),
        ),
        migrations.AddField(
            model_name="honorairesmedecin",
            name="convention",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="honoraires_medecins",
                to="medical.convention",
                verbose_name="Convention appliquée",
            ),
        ),
        migrations.AddField(
            model_name="honorairesmedecin",
            name="medecin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="honoraires_configures",
                to="medecin.medecin",
                verbose_name="Médecin",
            ),
        ),
        migrations.AddField(
            model_name="locationbloc",
            name="bloc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                to="medical.bloc",
                verbose_name="Bloc opératoire",
            ),
        ),
        migrations.AddField(
            model_name="locationbloc",
            name="cree_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locations_bloc_creees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="locationbloc",
            name="forfait",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                to="medical.forfait",
                verbose_name="Forfait appliqué",
            ),
        ),
        migrations.AddField(
            model_name="locationbloc",
            name="medecin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations_bloc",
                to="medecin.medecin",
                verbose_name="Médecin responsable",
            ),
        ),
        migrations.AddField(
            model_name="locationbloc",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations_bloc",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AddField(
            model_name="consommationproduitbloc",
            name="location",
            field=models.ForeignKey(
                help_text="Location de bloc associée",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consommations_produits",
                to="medical.locationbloc",
            ),
        ),
        migrations.AddField(
            model_name="locationblocacte",
            name="acte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                to="medical.actelocation",
            ),
        ),
        migrations.AddField(
            model_name="locationblocacte",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actes_location",
                to="medical.locationbloc",
            ),
        ),
        migrations.AddField(
            model_name="consommationproduitbloc",
            name="acte_associe",
            field=models.ForeignKey(
                blank=True,
                help_text="Acte associé si le produit provient d'un acte",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="medical.locationblocacte",
            ),
        ),
        migrations.AddField(
            model_name="prestationacte",
            name="acte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prestations_liees",
                to="medical.actekt",
            ),
        ),
        migrations.AddField(
            model_name="prestationacte",
            name="convention",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prestations",
                to="medical.convention",
                verbose_name="Convention appliquée",
            ),
        ),
        migrations.AddField(
            model_name="prestationkt",
            name="actes",
            field=models.ManyToManyField(
                related_name="prestations",
                through="medical.PrestationActe",
                to="medical.actekt",
                verbose_name="Actes médicaux",
            ),
        ),
        migrations.AddField(
            model_name="prestationkt",
            name="medecin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prestations",
                to="medecin.medecin",
                verbose_name="Médecin traitant",
            ),
        ),
        migrations.AddField(
            model_name="prestationkt",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prestations",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AddField(
            model_name="prestationacte",
            name="prestation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actes_details",
                to="medical.prestationkt",
            ),
        ),
        migrations.AddField(
            model_name="prixsupplementaireconfig",
            name="medecin",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prix_supplementaire_config",
                to="medecin.medecin",
                verbose_name="Médecin",
            ),
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rendez_vous_crees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="medecin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rendez_vous",
                to="medecin.medecin",
                verbose_name="Médecin",
            ),
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rendez_vous",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="medical.service",
            ),
        ),
        migrations.AddField(
            model_name="actekt",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actes",
                to="medical.service",
            ),
        ),
        migrations.AddField(
            model_name="tarifacte",
            name="acte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarifs",
                to="medical.actekt",
            ),
        ),
        migrations.AddField(
            model_name="tarifacte",
            name="convention",
            field=models.ForeignKey(
                blank=True,
                help_text="Convention appliquée. Si vide = tarif de base sans convention",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tarifs_acte",
                to="medical.convention",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="acteproduit",
            unique_together={("acte", "produit")},
        ),
        migrations.AlterUniqueTogether(
            name="acteproduitinclus",
            unique_together={("acte", "produit")},
        ),
        migrations.AlterUniqueTogether(
            name="blocproduitinclus",
            unique_together={("bloc", "produit")},
        ),
        migrations.AlterUniqueTogether(
            name="forfaitacteinclus",
            unique_together={("forfait", "acte")},
        ),
        migrations.AlterUniqueTogether(
            name="forfaitproduitinclus",
            unique_together={("forfait", "produit")},
        ),
        migrations.AlterUniqueTogether(
            name="honorairesmedecin",
            unique_together={("medecin", "acte", "convention")},
        ),
        migrations.AddIndex(
            model_name="locationbloc",
            index=models.Index(
                fields=["bloc", "date_operation"], name="medical_loc_bloc_id_ddbe36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locationbloc",
            index=models.Index(
                fields=["patient"], name="medical_loc_patient_4591bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locationbloc",
            index=models.Index(
                fields=["medecin"], name="medical_loc_medecin_4e9943_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locationbloc",
            index=models.Index(
                fields=["date_operation"], name="medical_loc_date_op_a1080f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="consommationproduitbloc",
            unique_together={
                ("location", "produit", "acte_associe", "source_inclusion")
            },
        ),
        migrations.AddIndex(
            model_name="prestationkt",
            index=models.Index(
                fields=["date_prestation"], name="medical_pre_date_pr_3ff750_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prestationkt",
            index=models.Index(fields=["statut"], name="medical_pre_statut_aa6658_idx"),
        ),
        migrations.AddIndex(
            model_name="prestationkt",
            index=models.Index(
                fields=["patient"], name="medical_pre_patient_986ba9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prestationkt",
            index=models.Index(
                fields=["medecin"], name="medical_pre_medecin_6aad25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prestationkt",
            index=models.Index(
                fields=["statut", "date_prestation"],
                name="medical_pre_statut_8fb56f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="rendezvous",
            constraint=models.UniqueConstraint(
                fields=("medecin", "date_heure"), name="unique_booking_per_doctor"
            ),
        ),
    ]
