# Generated by Django 5.1.7 on 2025-08-13 00:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0002_initial"),
        ("pharmacies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bloc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_bloc",
                    models.CharField(max_length=100, verbose_name="Nom du bloc"),
                ),
                (
                    "prix_base",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix pour les 90 premières minutes",
                        max_digits=10,
                        verbose_name="Prix de base (90 min)",
                    ),
                ),
                (
                    "prix_supplement_30min",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5000.00"),
                        max_digits=10,
                        verbose_name="Prix par tranche de 30 min supplémentaire",
                    ),
                ),
                (
                    "est_actif",
                    models.BooleanField(default=True, verbose_name="Bloc actif"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Bloc opératoire",
                "verbose_name_plural": "Blocs opératoires",
            },
        ),
        migrations.CreateModel(
            name="Forfait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Nom du forfait"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "prix",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix total du forfait",
                        max_digits=10,
                        verbose_name="Prix du forfait",
                    ),
                ),
                (
                    "duree",
                    models.PositiveIntegerField(
                        help_text="Durée totale couverte par le forfait",
                        verbose_name="Durée du forfait (en minutes)",
                    ),
                ),
                (
                    "est_actif",
                    models.BooleanField(default=True, verbose_name="Forfait actif"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Forfait",
                "verbose_name_plural": "Forfaits",
            },
        ),
        migrations.CreateModel(
            name="ForfaitProduitInclus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite",
                    models.PositiveIntegerField(default=1, verbose_name="Quantité"),
                ),
                (
                    "forfait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produits",
                        to="medical.forfait",
                        verbose_name="Forfait associé",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forfaits",
                        to="pharmacies.produit",
                        verbose_name="Produit associé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit de forfait",
                "verbose_name_plural": "Produits de forfait",
                "unique_together": {("forfait", "produit")},
            },
        ),
        migrations.CreateModel(
            name="LocationBlocPrestations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duree_reelle",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Durée réelle (minutes)",
                    ),
                ),
                (
                    "nom_acte",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        verbose_name="Nom de l'acte chirurgical",
                    ),
                ),
                (
                    "type_tarification",
                    models.CharField(
                        choices=[("FORFAIT", "Forfaitaire"), ("DUREE", "À la durée")],
                        default="DUREE",
                        max_length=10,
                        verbose_name="Type de tarification",
                    ),
                ),
                (
                    "prix_final",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Prix final",
                    ),
                ),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="Observations"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "bloc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="medical.bloc",
                        verbose_name="Bloc opératoire",
                    ),
                ),
                (
                    "forfait",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="medical.forfait",
                        verbose_name="Forfait appliqué",
                    ),
                ),
                (
                    "prestation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_bloc",
                        to="medical.prestation",
                        verbose_name="Prestation associée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location de bloc",
                "verbose_name_plural": "Locations de bloc",
                "indexes": [
                    models.Index(
                        fields=["bloc"], name="medical_loc_bloc_id_bfbb85_idx"
                    ),
                    models.Index(
                        fields=["prestation"], name="medical_loc_prestat_5dfba5_idx"
                    ),
                ],
            },
        ),
    ]
