# Generated by Django 5.1.7 on 2025-08-19 20:01

from django.db import migrations


def creer_medecins(apps, schema_editor):
    Medecin = apps.get_model("medecin", "Medecin")
    User = apps.get_model("auth", "User")
    admin = User.objects.first()

    noms = [
        "BOUGUELAA IMAD",
        "AZZI SOFIANE",
        "BOUZGHAIA SAADEDDINE",
        "MAAROUF MA",
        "KHIALI ZINE LABIDINE",
        "IMMOUNE SOFIANE",
        "FELLAH ADEL",
        "SIK AREZKI",
        "HADJ KALI HADJ",
        "CHAHRAOUI CHAH",
        "YAHIAOUI KADOUR",
        "ABUISSA AHMED",
        "SAIDANE MOURAD",
        "RAHMANI MOUSSAAB",
        "KERMEZLI AZIZ",
        "DEKKICHE SAMIR",
        "AZZOUZ ABDELMALEK",
        "KARA MAAMAR",
        "NACER BEY MUSTAPHA",
        "AIT MOKHETAR OMAR",
        "SALEM AMINE",
        "TOUATI MOHAMED",
        "NEDJAR REDOUANE",
        "NAIT ACHOUR NAIT",
        "BEN BOUAZIZ FOUAD",
        "BOUASRIA KHALED",
        "AZAZA ADEL",
        "LAMINE HABBOUCHI",
    ]

    for nom in noms:
        parts = nom.split()
        last_name = parts[0].capitalize()
        first_name = " ".join(parts[1:]).capitalize() if len(parts) > 1 else ""
        Medecin.objects.get_or_create(
            first_name=first_name, last_name=last_name, created_by=admin
        )


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0002_initial"),
    ]

    operations = [
        migrations.RunPython(creer_medecins),
    ]
