# Generated by Django 5.1.7 on 2025-04-23 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_initial"),
        ("medical", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prestation",
            name="convention",
        ),
        migrations.AddField(
            model_name="prestationacte",
            name="convention",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prestations",
                to="finance.convention",
                verbose_name="Convention appliquée",
            ),
        ),
    ]
