# Generated by Django 5.1.7 on 2025-05-01 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0002_initial"),
        ("pharmacies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActeProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite_defaut",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Quantité par défaut"
                    ),
                ),
                (
                    "acte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produits_defaut",
                        to="medical.acte",
                        verbose_name="Acte médical",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacies.produit",
                        verbose_name="Produit associé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit par défaut pour acte",
                "verbose_name_plural": "Produits par défaut pour actes",
                "unique_together": {("acte", "produit")},
            },
        ),
    ]
