# Generated by Django 5.1.7 on 2025-07-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="est_actif",
            field=models.BooleanField(default=True),
        ),
    ]
