# Generated by Django 5.1.7 on 2025-08-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0003_import_medecins"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestationacte",
            name="dossier_convention_complet",
            field=models.BooleanField(
                default=False,
                help_text="Le dossier administratif de convention est-il complet et valide ?",
                verbose_name="Dossier de convention complet",
            ),
        ),
        migrations.AlterField(
            model_name="prestationacte",
            name="convention_accordee",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="La convention a-t-elle été accordée au patient ?",
                null=True,
                verbose_name="Convention accordée",
            ),
        ),
    ]
