# Generated by Django 5.1.7 on 2025-08-13 00:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0003_bloc_forfait_forfaitproduitinclus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationblocprestations",
            name="date_operation",
            field=models.DateField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Date de l'opération",
            ),
            preserve_default=False,
        ),
    ]
