# Generated by Django 5.1.7 on 2025-04-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0003_remove_prestation_convention_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prestation",
            options={
                "ordering": ["-date_prestation"],
                "permissions": [
                    ("valider_prestation", "Peut valider une prestation"),
                    ("facturer_prestation", "Peut facturer une prestation"),
                ],
                "verbose_name": "Prestation médicale",
                "verbose_name_plural": "Prestations médicales",
            },
        ),
        migrations.RemoveField(
            model_name="prestation",
            name="date_facturation",
        ),
        migrations.RemoveField(
            model_name="prestation",
            name="prise_en_charge",
        ),
        migrations.RemoveField(
            model_name="prestation",
            name="reste_a_charge",
        ),
        migrations.RemoveField(
            model_name="prestation",
            name="taux_remboursement",
        ),
        migrations.RemoveField(
            model_name="prestationacte",
            name="quantite",
        ),
        migrations.RemoveField(
            model_name="prestationacte",
            name="remboursable",
        ),
        migrations.AlterField(
            model_name="prestation",
            name="statut",
            field=models.CharField(
                choices=[
                    ("PLANIFIE", "Planifié"),
                    ("REALISE", "Réalisé"),
                    ("FACTURE", "Facturé"),
                    ("ANNULE", "Annulé"),
                ],
                default="PLANIFIE",
                max_length=25,
                verbose_name="Statut de la prestation",
            ),
        ),
    ]
