# Generated by Django 5.1.7 on 2025-05-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0003_acteproduit"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="est_stockeur",
            field=models.BooleanField(default=False),
        ),
    ]
