# Generated by Django 5.1.7 on 2025-04-23 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0004_alter_prestation_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prestation",
            options={
                "ordering": ["-date_prestation"],
                "verbose_name": "Prestation médicale",
                "verbose_name_plural": "Prestations médicales",
            },
        ),
    ]
