# Generated by Django 5.1.7 on 2025-08-20 19:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0004_prestationacte_dossier_convention_complet_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FactureConventionKT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Montant total de la facture",
                    ),
                ),
                (
                    "date_facture",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de la facture"
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture Convention KT",
                "verbose_name_plural": "Factures Conventions KT",
            },
        ),
        migrations.CreateModel(
            name="PaiementActe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Montant du paiement",
                    ),
                ),
                ("date_paiement", models.DateField(verbose_name="Date de paiement")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'enregistrement"
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement d'acte",
                "verbose_name_plural": "Paiements d'actes",
                "ordering": ["-date_paiement", "-date_creation"],
            },
        ),
        migrations.AddField(
            model_name="prestationacte",
            name="date_facturation",
            field=models.DateField(
                blank=True,
                help_text="Date d'envoi de la facture à l'assurance",
                null=True,
                verbose_name="Date de facturation",
            ),
        ),
        migrations.AddField(
            model_name="prestationacte",
            name="date_rejet",
            field=models.DateField(blank=True, null=True, verbose_name="Date de rejet"),
        ),
        migrations.AddField(
            model_name="prestationacte",
            name="montant_recu",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Somme de tous les paiements reçus",
                max_digits=10,
                verbose_name="Montant total reçu",
            ),
        ),
        migrations.AddField(
            model_name="prestationacte",
            name="motif_rejet",
            field=models.TextField(
                blank=True,
                help_text="Raison du rejet par l'assurance",
                verbose_name="Motif de rejet",
            ),
        ),
        migrations.AddField(
            model_name="prestationacte",
            name="statut_facturation",
            field=models.CharField(
                choices=[
                    ("NON_FACTURABLE", "Non facturable"),
                    ("A_FACTURER", "À facturer"),
                    ("FACTURE", "Facturé"),
                    ("PAYE", "Payé"),
                    ("PAIEMENT_PARTIEL", "Paiement partiel"),
                    ("REJETE", "Rejeté par l'assurance"),
                    ("EN_LITIGE", "En litige"),
                    ("ANNULE", "Annulé"),
                ],
                default="NON_FACTURABLE",
                help_text="Statut du processus de facturation de l'acte",
                max_length=20,
                verbose_name="Statut de facturation",
            ),
        ),
        migrations.AddIndex(
            model_name="prestationacte",
            index=models.Index(
                fields=["statut_facturation"], name="medical_pre_statut__1ca693_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prestationacte",
            index=models.Index(
                fields=["date_facturation"], name="medical_pre_date_fa_0175b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prestationacte",
            index=models.Index(
                fields=["statut_facturation", "date_facturation"],
                name="medical_pre_statut__ecc5ba_idx",
            ),
        ),
        migrations.AddField(
            model_name="factureconventionkt",
            name="convention",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="factures_convention",
                to="medical.convention",
                verbose_name="Convention appliquée",
            ),
        ),
        migrations.AddField(
            model_name="factureconventionkt",
            name="prestation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="factures_convention",
                to="medical.prestationkt",
                verbose_name="Prestation liée",
            ),
        ),
        migrations.AddField(
            model_name="paiementacte",
            name="cree_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="paiementacte",
            name="prestation_acte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paiements",
                to="medical.prestationacte",
                verbose_name="Acte concerné",
            ),
        ),
        migrations.AddIndex(
            model_name="paiementacte",
            index=models.Index(
                fields=["date_paiement"], name="medical_pai_date_pa_2c5775_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paiementacte",
            index=models.Index(
                fields=["prestation_acte", "date_paiement"],
                name="medical_pai_prestat_2fd316_idx",
            ),
        ),
    ]
