# Generated by Django 5.1.7 on 2025-07-02 12:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0004_service_est_stockeur"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestation",
            name="prix_supplementaire",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Coût supplémentaire pour la prestation (hors actes et consommations)",
                max_digits=10,
                verbose_name="Frais supplémentaires",
            ),
        ),
    ]
