# Generated by Django 5.1.7 on 2025-08-13 01:10

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0004_locationblocprestations_date_operation"),
    ]

    operations = [

        migrations.AlterField(
            model_name="locationblocprestations",
            name="duree_reelle",
            field=models.PositiveIntegerField(
                default=90,
                help_text="Durée réelle de l'opération (obligatoire pour tarification à la durée et pour forfait)",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Durée réelle (minutes)",
            ),
            preserve_default=False,
        ),
    ]
