# Generated by Django 5.1.7 on 2025-04-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0005_alter_prestation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestationacte",
            name="honoraire_medecin",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Honoraire médecin",
            ),
        ),
    ]
