# Generated by Django 5.1.7 on 2025-07-04 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0005_prestation_prix_supplementaire"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrestationAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "champ",
                    models.CharField(max_length=100, verbose_name="Champ modifié"),
                ),
                (
                    "ancienne_valeur",
                    models.TextField(
                        blank=True, null=True, verbose_name="Valeur avant modification"
                    ),
                ),
                (
                    "nouvelle_valeur",
                    models.TextField(
                        blank=True, null=True, verbose_name="Valeur après modification"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "prestation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audits",
                        to="medical.prestation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit de prestation",
                "verbose_name_plural": "Audits de prestations",
                "ordering": ["-date_modification"],
            },
        ),
    ]
