# Generated by Django 5.1.7 on 2025-08-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0005_factureconventionkt_paiementacte_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paiementacte",
            name="cree_par",
        ),
        migrations.RemoveField(
            model_name="paiementacte",
            name="prestation_acte",
        ),
        migrations.RemoveField(
            model_name="prestationacte",
            name="montant_recu",
        ),
        migrations.AddField(
            model_name="prestationacte",
            name="date_paiement",
            field=models.DateField(
                blank=True,
                help_text="Date de réception du paiement",
                null=True,
                verbose_name="Date de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="prestationacte",
            name="statut_facturation",
            field=models.CharField(
                choices=[
                    ("NON_FACTURABLE", "Non facturable"),
                    ("A_FACTURER", "À facturer"),
                    ("FACTURE", "Facturé"),
                    ("PAYE", "Payé"),
                    ("REJETE", "Rejeté"),
                    ("ANNULE", "Annulé"),
                ],
                default="NON_FACTURABLE",
                help_text="Statut du processus de facturation de l'acte",
                max_length=20,
                verbose_name="Statut de facturation",
            ),
        ),
        migrations.AddIndex(
            model_name="prestationacte",
            index=models.Index(
                fields=["date_paiement"], name="medical_pre_date_pa_c51cda_idx"
            ),
        ),
        migrations.DeleteModel(
            name="PaiementActe",
        ),
    ]
