# Generated by Django 5.1.7 on 2025-08-21 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0006_remove_paiementacte_cree_par_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prestationacte",
            options={
                "permissions": (
                    ("facturer_prestationacte", "Peut facturer les actes"),
                    ("payer_prestationacte", "Peut marquer comme payé les actes"),
                    ("rejeter_prestationacte", "Peut rejeter les actes"),
                ),
                "verbose_name": "Détail d'acte",
                "verbose_name_plural": "Détails des actes",
            },
        ),
        migrations.AlterModelOptions(
            name="prestationkt",
            options={
                "ordering": ["-date_prestation"],
                "permissions": (
                    ("planifier_prestationkt", "Peut planifier des prestations"),
                    ("realiser_prestationkt", "Peut réaliser des prestations"),
                    ("payer_prestationkt", "Peut marquer comme payé les prestations"),
                    ("annuler_prestationkt", "Peut annuler des prestations"),
                ),
                "verbose_name": "PrestationKt médicale",
                "verbose_name_plural": "Prestations médicales",
            },
        ),
        migrations.DeleteModel(
            name="FactureConventionKT",
        ),
    ]
