# Generated by Django 5.1.7 on 2025-07-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0006_prestationaudit"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestation",
            name="prix_supplementaire_medecin",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Part médecin du supplément",
            ),
        ),
    ]
