# Generated by Django 5.1.7 on 2025-04-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0006_prestationacte_honoraire_medecin"),
    ]

    operations = [
 

        migrations.AlterField(
            model_name="prestation",
            name="prix_total",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Coût total"
            ),
        ),
        migrations.AlterField(
            model_name="prestationacte",
            name="honoraire_medecin",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Honoraire médecin"
            ),
        ),
    ]
