# Generated by Django 5.1.7 on 2025-08-14 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0006_locationbloc_locationblocaudit_and_more"),
        ("pharmacies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locationbloc",
            name="prestation_liee",
        ),
        migrations.CreateModel(
            name="ConsommationProduitBloc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField(default=1)),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
                ("montant_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consommations_produits",
                        to="medical.locationbloc",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacies.produit",
                    ),
                ),
            ],
        ),
    ]
