# Generated by Django 5.1.7 on 2025-08-22 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0007_alter_prestationacte_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actekt",
            options={
                "permissions": (
                    ("view_tarifs_acte", "Peut voir les tarifs des actes"),
                    ("manage_tarifs_acte", "Peut gérer les tarifs des actes"),
                    ("view_produits_acte", "Peut voir les produits associés aux actes"),
                ),
                "verbose_name": "Acte Kt",
                "verbose_name_plural": "Actes Kt",
            },
        ),
        migrations.AlterModelOptions(
            name="prestationacte",
            options={
                "permissions": (
                    ("facturer_prestationacte", "Peut facturer les actes"),
                    ("payer_prestationacte", "Peut marquer comme payé les actes"),
                    ("rejeter_prestationacte", "Peut rejeter les actes"),
                    (
                        "view_facturation_details",
                        "Peut voir les détails de facturation",
                    ),
                    ("manage_conventions", "Peut gérer les conventions"),
                ),
                "verbose_name": "Détail d'acte",
                "verbose_name_plural": "Détails des actes",
            },
        ),
        migrations.AlterModelOptions(
            name="prestationkt",
            options={
                "ordering": ["-date_prestation"],
                "permissions": (
                    ("planifier_prestationkt", "Peut planifier des prestations"),
                    ("realiser_prestationkt", "Peut réaliser des prestations"),
                    ("payer_prestationkt", "Peut marquer comme payé les prestations"),
                    ("annuler_prestationkt", "Peut annuler des prestations"),
                    ("view_all_prestationkt", "Peut voir toutes les prestations"),
                    ("export_prestationkt", "Peut exporter les prestations"),
                    (
                        "change_status_prestationkt",
                        "Peut changer le statut des prestations",
                    ),
                    ("generate_bon_paiement", "Peut générer les bons de paiement"),
                    ("view_patient_history", "Peut voir l'historique patient"),
                ),
                "verbose_name": "PrestationKt médicale",
                "verbose_name_plural": "Prestations médicales",
            },
        ),
        migrations.AlterModelOptions(
            name="tarifacte",
            options={
                "ordering": ["-is_default", "-date_effective"],
                "permissions": (
                    ("set_default_tarif", "Peut définir les tarifs par défaut"),
                    ("view_all_tarifs", "Peut voir tous les tarifs"),
                    ("manage_tarifs_history", "Peut gérer l'historique des tarifs"),
                ),
                "verbose_name": "Tarif d'acte",
                "verbose_name_plural": "Tarifs d'actes",
            },
        ),
    ]
