# Generated by Django 5.1.7 on 2025-04-24 11:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0007_prestation_honoraire_total_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestationacte",
            name="honoraire_medecin",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("99999999.99")),
                ],
                verbose_name="Honoraire médecin",
            ),
        ),
    ]
