# Generated by Django 5.1.7 on 2025-07-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0007_prestation_prix_supplementaire_medecin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prestation",
            name="honoraire_total",
        ),
    ]
