# Generated by Django 5.1.7 on 2025-08-14 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medecin", "0002_initial"),
        ("medical", "0007_remove_locationbloc_prestation_liee_and_more"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="locationbloc",
            name="unique_bloc_datetime_active",
        ),
        migrations.AddConstraint(
            model_name="locationbloc",
            constraint=models.UniqueConstraint(
                fields=("bloc", "date_operation", "heure_debut"),
                name="unique_bloc_datetime",
            ),
        ),
    ]
