# Generated by Django 5.1.7 on 2025-08-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0008_remove_locationbloc_unique_bloc_datetime_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="forfaitproduitinclus",
            options={
                "verbose_name": "Produit inclus dans le forfait",
                "verbose_name_plural": "Produits inclus dans les forfaits",
            },
        ),
        migrations.AlterUniqueTogether(
            name="forfaitproduitinclus",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="consommationproduitbloc",
            name="est_inclus",
            field=models.BooleanField(default=False),
        ),
    ]
