# Generated by Django 5.1.7 on 2025-04-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0008_alter_prestationacte_honoraire_medecin"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestation",
            name="honoraire_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Honoraire médecin total",
            ),
        ),
    ]
