# Generated by Django 5.1.7 on 2025-08-22 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0008_alter_actekt_options_alter_prestationacte_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prestationacte",
            options={
                "permissions": (
                    ("facturer_prestationacte", "Peut facturer les actes"),
                    ("payer_prestationacte", "Peut marquer comme payé les actes"),
                    ("rejeter_prestationacte", "Peut rejeter les actes"),
                    (
                        "view_facturation_details",
                        "Peut voir les détails de facturation",
                    ),
                    ("manage_conventions", "Peut gérer les conventions"),
                    ("manage_paiements_especes", "Peut gérer les paiements espèces"),
                    ("view_paiements_especes", "Peut consulter les paiements espèces"),
                    ("encaisser_especes", "Peut encaisser les paiements espèces"),
                    (
                        "supprimer_paiements_especes",
                        "Peut supprimer les paiements espèces",
                    ),
                ),
                "verbose_name": "Détail d'acte",
                "verbose_name_plural": "Détails des actes",
            },
        ),
    ]
