# Generated by Django 5.1.7 on 2025-08-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0009_alter_prestationacte_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="convention",
            options={
                "permissions": (
                    ("approve_convention", "Peut approuver une convention"),
                    ("reject_convention", "Peut rejeter une convention"),
                    (
                        "manage_dossier_convention",
                        "Peut gérer les dossiers de convention",
                    ),
                    (
                        "view_convention_stats",
                        "Peut voir les statistiques des conventions",
                    ),
                ),
                "verbose_name": "Convention KT",
                "verbose_name_plural": "Conventions KT",
            },
        ),
        migrations.AlterModelOptions(
            name="prestationkt",
            options={
                "ordering": ["-date_prestation"],
                "permissions": (
                    ("planifier_prestationkt", "Peut planifier des prestations"),
                    ("realiser_prestationkt", "Peut réaliser des prestations"),
                    ("payer_prestationkt", "Peut marquer comme payé les prestations"),
                    ("annuler_prestationkt", "Peut annuler des prestations"),
                    ("view_all_prestationkt", "Peut voir toutes les prestations"),
                    ("export_prestationkt", "Peut exporter les prestations"),
                    (
                        "change_status_prestationkt",
                        "Peut changer le statut des prestations",
                    ),
                    ("generate_bon_paiement", "Peut générer les bons de paiement"),
                    ("view_patient_history", "Peut voir l'historique patient"),
                    ("manage_paiements_especes", "Peut gérer les paiements espèces"),
                    ("view_paiements_especes", "Peut consulter les paiements espèces"),
                    ("encaisser_especes", "Peut encaisser les paiements espèces"),
                    (
                        "supprimer_paiements_especes",
                        "Peut supprimer les paiements espèces",
                    ),
                    (
                        "view_dashboard_especes",
                        "Peut voir le dashboard des paiements espèces",
                    ),
                ),
                "verbose_name": "PrestationKt médicale",
                "verbose_name_plural": "Prestations médicales",
            },
        ),
    ]
