# Generated by Django 5.1.7 on 2025-08-14 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0010_rename_acte_to_actekt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actekt",
            options={"verbose_name": "ActeKt", "verbose_name_plural": "Actes"},
        ),
        migrations.AlterField(
            model_name="acteproduit",
            name="acte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produits_defaut",
                to="medical.actekt",
                verbose_name="ActeKt médical",
            ),
        ),
    ]
