# Generated by Django 5.1.7 on 2025-08-24 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0010_alter_convention_options_alter_prestationkt_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="actelocation",
            old_name="est_actif",
            new_name="est_active",
        ),
        migrations.RenameField(
            model_name="bloc",
            old_name="est_actif",
            new_name="est_active",
        ),
        migrations.RenameField(
            model_name="forfait",
            old_name="est_actif",
            new_name="est_active",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="est_actif",
            new_name="est_active",
        ),
    ]
