# Generated by Django 5.1.7 on 2025-04-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0010_prestation_honoraire_total"),
        ("medical", "0011_clean_honoraire_medecin"),
    ]

    operations = []
