# Generated by Django 5.1.7 on 2025-08-27 00:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0011_rename_est_actif_actelocation_est_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="seuil_sejour_court_heures",
            field=models.PositiveSmallIntegerField(
                default=24,
                help_text="Durée en heures en dessous de laquelle le tarif fixe s'applique (défaut: 24h)",
                verbose_name="Seuil séjour court (heures)",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="tarif_fixe_sejour_court",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("7000.00"),
                help_text="Montant fixe facturé pour les séjours de moins de 24h dans ce service",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Tarif fixe séjour court (DA)",
            ),
        ),
    ]
