# Generated by Django 5.1.7 on 2025-08-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_delete_tarif_gardes"),
        ("medecin", "0002_initial"),
        ("medical", "0011_alter_actekt_options_alter_acteproduit_acte"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Prestation",
            new_name="PrestationKt",
        ),
        migrations.AlterModelOptions(
            name="prestationkt",
            options={
                "ordering": ["-date_prestation"],
                "verbose_name": "PrestationKt médicale",
                "verbose_name_plural": "Prestations médicales",
            },
        ),
        migrations.RenameIndex(
            model_name="prestationkt",
            new_name="medical_pre_date_pr_3ff750_idx",
            old_name="medical_pre_date_pr_25cb1c_idx",
        ),
        migrations.RenameIndex(
            model_name="prestationkt",
            new_name="medical_pre_statut_aa6658_idx",
            old_name="medical_pre_statut_32b6cc_idx",
        ),
        migrations.RenameIndex(
            model_name="prestationkt",
            new_name="medical_pre_patient_986ba9_idx",
            old_name="medical_pre_patient_154bca_idx",
        ),
    ]
