# Generated by Django 5.1.7 on 2025-08-14 18:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0012_rename_prestation_prestationkt_and_more"),
        ("pharmacies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActeLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom de l'acte chirurgical ou interventionnel",
                        max_length=255,
                        verbose_name="Nom de l'acte",
                    ),
                ),
                (
                    "prix",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix de base de l'acte sans les suppléments",
                        max_digits=10,
                        verbose_name="Prix de l'acte",
                    ),
                ),
                (
                    "duree_estimee",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Durée estimée pour cet acte",
                        null=True,
                        verbose_name="Durée estimée (minutes)",
                    ),
                ),
                (
                    "est_actif",
                    models.BooleanField(default=True, verbose_name="Acte actif"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description de l'acte"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Acte de location",
                "verbose_name_plural": "Actes de location",
                "ordering": ["nom"],
            },
        ),
        migrations.AlterModelOptions(
            name="consommationproduitbloc",
            options={
                "ordering": ["-date_consommation"],
                "verbose_name": "Consommation de produit",
                "verbose_name_plural": "Consommations de produits",
            },
        ),
        migrations.AddField(
            model_name="consommationproduitbloc",
            name="date_consommation",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de consommation",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="consommationproduitbloc",
            name="est_inclus",
            field=models.BooleanField(
                default=False,
                help_text="Indique si ce produit est inclus dans le forfait ou l'acte",
                verbose_name="Inclus dans le forfait/acte",
            ),
        ),
        migrations.AlterField(
            model_name="consommationproduitbloc",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consommations_produits",
                to="medical.locationbloc",
                verbose_name="Location de bloc",
            ),
        ),
        migrations.AlterField(
            model_name="consommationproduitbloc",
            name="montant_total",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Montant total"
            ),
        ),
        migrations.AlterField(
            model_name="consommationproduitbloc",
            name="prix_unitaire",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Prix unitaire"
            ),
        ),
        migrations.AlterField(
            model_name="consommationproduitbloc",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="pharmacies.produit",
                verbose_name="Produit consommé",
            ),
        ),
        migrations.AlterField(
            model_name="consommationproduitbloc",
            name="quantite",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Quantité consommée"
            ),
        ),
        migrations.AlterField(
            model_name="locationbloc",
            name="type_tarification",
            field=models.CharField(
                choices=[
                    ("FORFAIT", "Forfaitaire"),
                    ("DUREE", "À la durée"),
                    ("ACTE", "Par acte"),
                ],
                default="DUREE",
                max_length=10,
                verbose_name="Type de tarification",
            ),
        ),
        migrations.AlterField(
            model_name="locationblocaudit",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audits",
                to="medical.locationbloc",
                verbose_name="Location concernée",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="forfaitproduitinclus",
            unique_together={("forfait", "produit")},
        ),
        migrations.AddField(
            model_name="locationbloc",
            name="acte_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Acte prédéfini si applicable",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations_bloc",
                to="medical.actelocation",
                verbose_name="Acte standardisé",
            ),
        ),
        migrations.CreateModel(
            name="ActeLocationProduitInclus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite_standard",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Quantité généralement utilisée pour cet acte",
                        verbose_name="Quantité standard",
                    ),
                ),
                (
                    "est_obligatoire",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si ce produit est obligatoire pour cet acte",
                        verbose_name="Produit obligatoire",
                    ),
                ),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordre d'affichage dans la liste des produits",
                        verbose_name="Ordre d'affichage",
                    ),
                ),
                (
                    "acte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produits_inclus",
                        to="medical.actelocation",
                        verbose_name="Acte associé",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actes_utilisant",
                        to="pharmacies.produit",
                        verbose_name="Produit inclus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit inclus dans l'acte",
                "verbose_name_plural": "Produits inclus dans les actes",
                "ordering": ["ordre", "produit__nom"],
                "unique_together": {("acte", "produit")},
            },
        ),
        migrations.CreateModel(
            name="ForfaitActeLocationInclus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Nombre de fois que cet acte est inclus dans le forfait",
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "prix_unitaire_forfait",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Prix unitaire de cet acte dans le contexte du forfait (peut différer du prix standard)",
                        max_digits=10,
                        null=True,
                        verbose_name="Prix unitaire dans le forfait",
                    ),
                ),
                (
                    "est_principal",
                    models.BooleanField(
                        default=False,
                        help_text="Indique si c'est l'acte principal du forfait",
                        verbose_name="Acte principal",
                    ),
                ),
                (
                    "acte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forfaits_inclus",
                        to="medical.actelocation",
                        verbose_name="Acte inclus",
                    ),
                ),
                (
                    "forfait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actes_inclus",
                        to="medical.forfait",
                        verbose_name="Forfait associé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acte inclus dans le forfait",
                "verbose_name_plural": "Actes inclus dans les forfaits",
                "unique_together": {("forfait", "acte")},
            },
        ),
    ]
