# Generated by Django 5.1.7 on 2025-04-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0012_merge_20250424_1236"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestationacte",
            name="convention_accordee",
            field=models.BooleanField(
                default=False, verbose_name="Convention accordée"
            ),
        ),
    ]
