# Generated by Django 5.1.7 on 2025-08-15 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medecin", "0002_initial"),
        ("medical", "0013_actelocation_alter_consommationproduitbloc_options_and_more"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationBlocActe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField(default=1)),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
                ("prix_total", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "Acte dans une location de bloc",
                "verbose_name_plural": "Actes dans les locations de bloc",
            },
        ),
        migrations.AlterUniqueTogether(
            name="actelocationproduitinclus",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="actelocationproduitinclus",
            name="acte",
        ),
        migrations.RemoveField(
            model_name="actelocationproduitinclus",
            name="produit",
        ),
        migrations.AlterUniqueTogether(
            name="forfaitactelocationinclus",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="forfaitactelocationinclus",
            name="acte",
        ),
        migrations.RemoveField(
            model_name="forfaitactelocationinclus",
            name="forfait",
        ),
        migrations.RemoveField(
            model_name="locationblocaudit",
            name="location",
        ),
        migrations.RemoveField(
            model_name="locationblocaudit",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="consommationproduitbloc",
            options={
                "verbose_name": "Consommation de produit",
                "verbose_name_plural": "Consommations de produits",
            },
        ),
        migrations.RemoveConstraint(
            model_name="locationbloc",
            name="unique_bloc_datetime",
        ),
        migrations.RemoveField(
            model_name="consommationproduitbloc",
            name="date_consommation",
        ),
        migrations.RemoveField(
            model_name="consommationproduitbloc",
            name="est_inclus",
        ),
        migrations.RemoveField(
            model_name="locationbloc",
            name="duree_prevue",
        ),
        migrations.RemoveField(
            model_name="locationbloc",
            name="heure_debut",
        ),
        migrations.RemoveField(
            model_name="locationbloc",
            name="heure_fin",
        ),
        migrations.AddField(
            model_name="locationbloc",
            name="heure_operation",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Heure de l'opération"
            ),
        ),
        migrations.RemoveField(
            model_name="locationbloc",
            name="acte_location",
        ),
        migrations.AlterField(
            model_name="locationbloc",
            name="type_tarification",
            field=models.CharField(
                choices=[("FORFAIT", "Forfaitaire"), ("DUREE", "À la durée")],
                default="DUREE",
                max_length=10,
                verbose_name="Type de tarification",
            ),
        ),
        migrations.AddField(
            model_name="locationblocacte",
            name="acte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                to="medical.actelocation",
            ),
        ),
        migrations.AddField(
            model_name="locationblocacte",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actes_location",
                to="medical.locationbloc",
            ),
        ),
        migrations.AddConstraint(
            model_name="locationbloc",
            constraint=models.UniqueConstraint(
                fields=("bloc", "date_operation"), name="unique_bloc_datetime"
            ),
        ),
        migrations.DeleteModel(
            name="ActeLocationProduitInclus",
        ),
        migrations.DeleteModel(
            name="ForfaitActeLocationInclus",
        ),
        migrations.DeleteModel(
            name="LocationBlocAudit",
        ),
        migrations.AddField(
            model_name="locationbloc",
            name="acte_location",
            field=models.ManyToManyField(
                related_name="locations_bloc",
                through="medical.LocationBlocActe",
                to="medical.actelocation",
            ),
        ),
    ]
