# Generated by Django 5.1.7 on 2025-04-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0013_prestationacte_convention_accordee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestationacte",
            name="convention_accordee",
            field=models.BooleanField(
                blank=True,
                help_text="Uniquement si une convention est sélectionnée",
                null=True,
                verbose_name="Statut Convention",
            ),
        ),
    ]
