# Generated by Django 5.1.7 on 2025-08-15 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medecin", "0002_initial"),
        ("medical", "0014_locationblocacte_and_more"),
        ("patients", "0001_initial"),
        ("pharmacies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActeProduitInclus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite_standard",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Quantité standard"
                    ),
                ),
                (
                    "est_obligatoire",
                    models.BooleanField(
                        default=True, verbose_name="Produit obligatoire"
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit inclus dans l'acte",
                "verbose_name_plural": "Produits inclus dans les actes",
            },
        ),
        migrations.CreateModel(
            name="BlocProduitInclus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Quantité incluse"
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit inclus dans le bloc",
                "verbose_name_plural": "Produits inclus dans les blocs",
            },
        ),
        migrations.RemoveConstraint(
            model_name="locationbloc",
            name="unique_bloc_datetime",
        ),
        migrations.RemoveIndex(
            model_name="locationbloc",
            name="medical_loc_statut_6de97e_idx",
        ),
        migrations.RemoveIndex(
            model_name="locationbloc",
            name="medical_loc_date_op_3eed7d_idx",
        ),
        migrations.RemoveField(
            model_name="locationbloc",
            name="acte_location",
        ),
        migrations.RemoveField(
            model_name="locationbloc",
            name="statut",
        ),
        migrations.AddField(
            model_name="consommationproduitbloc",
            name="est_inclus",
            field=models.BooleanField(
                default=False,
                help_text="Indique si le produit est inclus dans le forfait/bloc/acte",
                verbose_name="Produit inclus",
            ),
        ),
        migrations.AddField(
            model_name="consommationproduitbloc",
            name="source_inclusion",
            field=models.CharField(
                choices=[
                    ("BLOC", "Inclus dans le bloc"),
                    ("FORFAIT", "Inclus dans le forfait"),
                    ("ACTE", "Inclus dans l'acte"),
                    ("SUPPLEMENTAIRE", "Supplémentaire"),
                ],
                default="SUPPLEMENTAIRE",
                max_length=20,
                verbose_name="Source d'inclusion",
            ),
        ),
        migrations.AddIndex(
            model_name="locationbloc",
            index=models.Index(
                fields=["date_operation"], name="medical_loc_date_op_a1080f_idx"
            ),
        ),
        migrations.AddField(
            model_name="acteproduitinclus",
            name="acte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produits_inclus",
                to="medical.actelocation",
                verbose_name="Acte",
            ),
        ),
        migrations.AddField(
            model_name="acteproduitinclus",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pharmacies.produit",
                verbose_name="Produit inclus",
            ),
        ),
        migrations.AddField(
            model_name="blocproduitinclus",
            name="bloc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produits_inclus",
                to="medical.bloc",
                verbose_name="Bloc",
            ),
        ),
        migrations.AddField(
            model_name="blocproduitinclus",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pharmacies.produit",
                verbose_name="Produit inclus",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="acteproduitinclus",
            unique_together={("acte", "produit")},
        ),
        migrations.AlterUniqueTogether(
            name="blocproduitinclus",
            unique_together={("bloc", "produit")},
        ),
    ]
