# Generated by Django 5.1.7 on 2025-04-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0014_alter_prestationacte_convention_accordee"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="prestationacte",
            unique_together=set(),
        ),
    ]
