# Generated by Django 5.1.7 on 2025-08-15 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0015_acteproduitinclus_blocproduitinclus_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationBlocAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "champ",
                    models.CharField(max_length=100, verbose_name="Champ modifié"),
                ),
                (
                    "ancienne_valeur",
                    models.TextField(blank=True, verbose_name="Ancienne valeur"),
                ),
                (
                    "nouvelle_valeur",
                    models.TextField(blank=True, verbose_name="Nouvelle valeur"),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audits",
                        to="medical.locationbloc",
                        verbose_name="Location de bloc",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit de location de bloc",
                "verbose_name_plural": "Audits de locations de bloc",
                "ordering": ["-date_modification"],
            },
        ),
    ]
