# Generated by Django 5.1.7 on 2025-08-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0016_locationblocaudit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationbloc",
            name="nom_acte",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Nom de l'acte chirurgical",
            ),
        ),
    ]
