# Generated by Django 5.1.7 on 2025-08-15 17:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0017_alter_locationbloc_nom_acte"),
        ("pharmacies", "0001_initial"),
    ]

    operations = [
        # 1) Ajouter d'abord les nouveaux champs nécessaires (acte_associe, date_creation, ecart_quantite, quantite_incluse)
        migrations.AddField(
            model_name="consommationproduitbloc",
            name="acte_associe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consommations_produits",
                to="medical.locationblocacte",
            ),
        ),
        migrations.AddField(
            model_name="consommationproduitbloc",
            name="date_creation",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consommationproduitbloc",
            name="ecart_quantite",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Écart = quantité consommée - quantité incluse",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="consommationproduitbloc",
            name="quantite_incluse",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Quantité incluse dans le prix de base",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        # 2) Puis appliquer les modifications/altérations sur les champs existants
        migrations.AlterField(
            model_name="consommationproduitbloc",
            name="est_inclus",
            field=models.BooleanField(
                default=False,
                help_text="True si aucun dépassement de la quantité incluse",
            ),
        ),
        migrations.AlterField(
            model_name="consommationproduitbloc",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consommations",
                to="medical.locationbloc",
            ),
        ),
        migrations.AlterField(
            model_name="consommationproduitbloc",
            name="prix_unitaire",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="consommationproduitbloc",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pharmacies.produit"
            ),
        ),
        migrations.AlterField(
            model_name="consommationproduitbloc",
            name="quantite",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Quantité réellement consommée",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="consommationproduitbloc",
            name="source_inclusion",
            field=models.CharField(
                choices=[
                    ("BLOC", "Inclus dans le bloc"),
                    ("FORFAIT", "Inclus dans le forfait"),
                    ("ACTE", "Inclus dans l'acte"),
                    ("ACTE_SUPPLEMENTAIRE", "Ajouté à l'acte"),
                    ("SUPPLEMENTAIRE", "Produit supplémentaire"),
                ],
                help_text="Source d'inclusion du produit",
                max_length=20,
            ),
        ),
        # 3) Alter de la table (si nécessaire)
        migrations.AlterModelTable(
            name="consommationproduitbloc",
            table="medical_consommation_produit_bloc",
        ),
        # 4) Maintenant que 'acte_associe' existe, appliquer la contrainte unique
        migrations.AlterUniqueTogether(
            name="consommationproduitbloc",
            unique_together={("location", "produit", "acte_associe")},
        ),
        # 5) Enfin supprimer l'ancien champ montant_total (s'il est présent)
        migrations.RemoveField(
            model_name="consommationproduitbloc",
            name="montant_total",
        ),
    ]
