# Generated by Django 5.1.7 on 2025-08-17 19:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0018_alter_consommationproduitbloc_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationbloc",
            name="complement_du_medecin",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Montant que le médecin doit payer à la clinique",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Complément dû par le médecin",
            ),
        ),
        migrations.AddField(
            model_name="locationbloc",
            name="date_reglement_complement",
            field=models.DateField(
                blank=True,
                help_text="Date à laquelle le médecin a payé le complément",
                null=True,
                verbose_name="Date de règlement du complément",
            ),
        ),
        migrations.AddField(
            model_name="locationbloc",
            name="date_reglement_surplus",
            field=models.DateField(
                blank=True,
                help_text="Date à laquelle le surplus a été versé au médecin",
                null=True,
                verbose_name="Date de règlement du surplus",
            ),
        ),
        migrations.AddField(
            model_name="locationbloc",
            name="difference_paiement",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Différence entre montant facturé et montant payé (+ = surplus, - = complément)",
                max_digits=10,
                verbose_name="Différence de paiement",
            ),
        ),
        migrations.AddField(
            model_name="locationbloc",
            name="montant_paye_caisse",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Montant effectivement reçu par la caisse",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Montant payé à la caisse",
            ),
        ),
        migrations.AddField(
            model_name="locationbloc",
            name="notes_paiement",
            field=models.TextField(
                blank=True,
                help_text="Notes relatives au paiement ou aux arrangements financiers",
                verbose_name="Notes sur le paiement",
            ),
        ),
        migrations.AddField(
            model_name="locationbloc",
            name="statut_paiement",
            field=models.CharField(
                choices=[
                    ("EQUILIBRE", "Équilibré"),
                    ("SURPLUS_CLINIQUE", "Surplus à verser au médecin"),
                    ("COMPLEMENT_MEDECIN", "Complément dû par le médecin"),
                    ("AUCUN_PAIEMENT", "Aucun paiement enregistré"),
                ],
                default="AUCUN_PAIEMENT",
                max_length=20,
                verbose_name="Statut du paiement",
            ),
        ),
        migrations.AddField(
            model_name="locationbloc",
            name="surplus_a_verser",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Montant que la clinique doit verser au médecin",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Surplus à verser au médecin",
            ),
        ),
    ]
