# Generated by Django 5.1.7 on 2025-08-18 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0019_locationbloc_complement_du_medecin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForfaitActeInclus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Nombre de fois que cet acte est inclus dans le forfait",
                        verbose_name="Quantité incluse",
                    ),
                ),
                (
                    "prix_unitaire_inclus",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Prix unitaire de l'acte tel qu'inclus dans le forfait (peut différer du prix standard)",
                        max_digits=10,
                        null=True,
                        verbose_name="Prix unitaire inclus",
                    ),
                ),
                (
                    "acte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forfaits_incluant",
                        to="medical.actelocation",
                        verbose_name="Acte inclus",
                    ),
                ),
                (
                    "forfait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actes_inclus",
                        to="medical.forfait",
                        verbose_name="Forfait",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acte inclus dans le forfait",
                "verbose_name_plural": "Actes inclus dans les forfaits",
                "unique_together": {("forfait", "acte")},
            },
        ),
    ]
