# Generated by Django 5.1.7 on 2025-08-18 13:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0020_forfaitacteinclus"),
        ("pharmacies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consommationproduitbloc",
            options={
                "ordering": ["location", "produit__nom"],
                "verbose_name": "Consommation de produit",
                "verbose_name_plural": "Consommations de produits",
            },
        ),
        migrations.AlterUniqueTogether(
            name="consommationproduitbloc",
            unique_together={
                ("location", "produit", "acte_associe", "source_inclusion")
            },
        ),
        migrations.AddField(
            model_name="consommationproduitbloc",
            name="date_consommation",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Date et heure de création de l'enregistrement",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consommationproduitbloc",
            name="notes",
            field=models.TextField(blank=True, help_text="Notes sur la consommation"),
        ),
        migrations.AlterField(
            model_name="consommationproduitbloc",
            name="acte_associe",
            field=models.ForeignKey(
                blank=True,
                help_text="Acte associé si le produit provient d'un acte",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="medical.locationblocacte",
            ),
        ),
        migrations.AlterField(
            model_name="consommationproduitbloc",
            name="ecart_quantite",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Écart entre quantité utilisée et incluse (calculé automatiquement)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="consommationproduitbloc",
            name="est_inclus",
            field=models.BooleanField(
                default=False,
                help_text="True si entièrement inclus (pas de supplément à facturer)",
            ),
        ),
        migrations.AlterField(
            model_name="consommationproduitbloc",
            name="location",
            field=models.ForeignKey(
                help_text="Location de bloc associée",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consommations_produits",
                to="medical.locationbloc",
            ),
        ),
        migrations.AlterField(
            model_name="consommationproduitbloc",
            name="prix_unitaire",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Prix unitaire du produit au moment de la consommation",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="consommationproduitbloc",
            name="produit",
            field=models.ForeignKey(
                help_text="Produit consommé",
                on_delete=django.db.models.deletion.CASCADE,
                to="pharmacies.produit",
            ),
        ),
        migrations.AlterField(
            model_name="consommationproduitbloc",
            name="quantite",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Quantité réellement utilisée",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="consommationproduitbloc",
            name="quantite_incluse",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Quantité incluse dans le forfait/bloc/acte",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="consommationproduitbloc",
            name="source_inclusion",
            field=models.CharField(
                choices=[
                    ("BLOC", "Inclus dans le bloc"),
                    ("FORFAIT", "Inclus dans le forfait"),
                    ("FORFAIT_ACTE", "Inclus via acte forfaitaire"),
                    ("FORFAIT_MIXTE", "Forfait + acte forfaitaire"),
                    ("ACTE", "Inclus dans un acte"),
                    ("ACTE_SUPPLEMENTAIRE", "Acte supplémentaire"),
                    ("SUPPLEMENTAIRE", "Produit supplémentaire"),
                    ("MIXTE", "Sources multiples"),
                ],
                default="SUPPLEMENTAIRE",
                help_text="Source d'inclusion du produit",
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="consommationproduitbloc",
            name="date_creation",
        ),
    ]
