# Generated by Django 5.1.7 on 2025-04-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medecin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialite",
                    models.CharField(
                        max_length=100, verbose_name="Spécialité médicale"
                    ),
                ),
                (
                    "numero_ordre",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numéro d'ordre"
                    ),
                ),
                (
                    "photo_profil",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="medecins/profiles/",
                        verbose_name="Photo de profil",
                    ),
                ),
                (
                    "disponible",
                    models.BooleanField(
                        default=True, verbose_name="Disponible pour consultations"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
            ],
            options={
                "verbose_name": "Médecin",
                "verbose_name_plural": "Médecins",
            },
        ),
    ]
