# Generated by Django 5.1.7 on 2025-07-09 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medecin", "0001_initial"),
        ("medical", "0001_initial"),
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medecin",
            name="personnel",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profil_medecin",
                to="rh.personnel",
                verbose_name="Profil du personnel",
            ),
        ),
        migrations.AddField(
            model_name="medecin",
            name="services",
            field=models.ManyToManyField(related_name="medecins", to="medical.service"),
        ),
    ]
