# Generated by Django 5.1.7 on 2025-08-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medecin", "0001_initial"),
        ("medical", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medecin",
            name="services",
            field=models.ManyToManyField(related_name="medecins", to="medical.service"),
        ),
    ]
