# Generated by Django 5.1.7 on 2025-08-17 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medecin", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medecin",
            name="telephone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le numéro de téléphone doit être au format +213123456789 (9 à 15 chiffres).",
                        regex="^\\+?\\d{9,15}$",
                    )
                ],
                verbose_name="Numéro de téléphone",
            ),
        ),
    ]
