# Generated by Django 5.1.7 on 2025-04-24 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medecin", "0002_initial"),
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medecin",
            name="personnel",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profil_medecin",
                to="rh.personnel",
                verbose_name="Profil du personnel",
            ),
        ),
    ]
