# Generated by Django 5.1.7 on 2025-08-17 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medecin", "0003_medecin_telephone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medecin",
            name="disponible",
        ),
        migrations.RemoveField(
            model_name="medecin",
            name="numero_ordre",
        ),
        migrations.RemoveField(
            model_name="medecin",
            name="personnel",
        ),
        migrations.RemoveField(
            model_name="medecin",
            name="photo_profil",
        ),
        migrations.AddField(
            model_name="medecin",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medecin",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="medecin",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Prénom"
            ),
        ),
        migrations.AddField(
            model_name="medecin",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Nom"
            ),
        ),
    ]
