# Generated by Django 5.1.7 on 2025-04-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medecin", "0003_alter_medecin_personnel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medecin",
            name="numero_ordre",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Numéro d'ordre",
            ),
        ),
        migrations.AlterField(
            model_name="medecin",
            name="specialite",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Spécialité médicale",
            ),
        ),
    ]
