# Generated by Django 5.1.7 on 2025-04-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("poste", models.CharField(max_length=255)),
                ("numero", models.CharField(blank=True, max_length=255, null=True)),
                ("statut_activite", models.BooleanField(default=True)),
                ("user_add", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "contacts",
                "managed": True,
            },
        ),
    ]
