# Generated by Django 5.1.7 on 2025-04-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annuaire", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contacts",
            name="status_phone",
        ),
        migrations.AddField(
            model_name="contacts",
            name="statut_activite",
            field=models.BooleanField(default=True),
        ),
    ]
