# Generated by Django 5.1.7 on 2025-08-09 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventaire", "0001_initial"),
        ("medical", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salle",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salles",
                to="medical.service",
            ),
        ),
        migrations.AddField(
            model_name="mouvementstock",
            name="salle_destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mouvements_entrants",
                to="inventaire.salle",
            ),
        ),
        migrations.AddField(
            model_name="inventaire",
            name="salle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventaires",
                to="inventaire.salle",
            ),
        ),
        migrations.AddField(
            model_name="demandetransfert",
            name="salle_destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transferts_entrants",
                to="inventaire.salle",
            ),
        ),
        migrations.AddField(
            model_name="demandetransfert",
            name="salle_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transferts_sortants",
                to="inventaire.salle",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="inventaire.item",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="salle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="inventaire.salle",
            ),
        ),
        migrations.AddField(
            model_name="mouvementstock",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mouvements",
                to="inventaire.stock",
            ),
        ),
        migrations.AddField(
            model_name="ligneinventaire",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventaire.stock"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salle",
            unique_together={("nom", "service")},
        ),
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together={("item", "salle")},
        ),
        migrations.AlterUniqueTogether(
            name="ligneinventaire",
            unique_together={("inventaire", "stock")},
        ),
    ]
