# Generated by Django 5.1.7 on 2025-08-09 00:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("track_create", models.BooleanField(default=True)),
                ("track_update", models.BooleanField(default=True)),
                ("track_delete", models.BooleanField(default=True)),
                ("track_view", models.BooleanField(default=False)),
                ("excluded_fields", models.JSONField(blank=True, default=list)),
                (
                    "content_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration d'audit",
                "verbose_name_plural": "Configurations d'audit",
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("successful", models.BooleanField(default=False)),
                ("failure_reason", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["username", "timestamp"],
                        name="audit_login_usernam_86a7ab_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="audit_login_ip_addr_8dc769_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Création"),
                            ("UPDATE", "Modification"),
                            ("DELETE", "Suppression"),
                            ("VIEW", "Consultation"),
                            ("LOGIN", "Connexion"),
                            ("LOGOUT", "Déconnexion"),
                            ("FAILED_LOGIN", "Tentative de connexion échouée"),
                            ("PERMISSION_DENIED", "Accès refusé"),
                            ("EXPORT", "Export de données"),
                            ("IMPORT", "Import de données"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("object_repr", models.CharField(blank=True, max_length=200)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("method", models.CharField(blank=True, max_length=10)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("app_label", models.CharField(blank=True, max_length=100)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log d'audit",
                "verbose_name_plural": "Logs d'audit",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="audit_audit_user_id_e8be02_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="audit_audit_action_2a1328_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="audit_audit_content_4c2ead_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="audit_audit_timesta_19e18a_idx"
                    ),
                ],
            },
        ),
    ]
