# Generated by Django 5.1.7 on 2025-04-21 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tarif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prix",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Prix (€)",
                    ),
                ),
                (
                    "salaire",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Salaire (€)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarif",
                "verbose_name_plural": "Tarifs",
            },
        ),
        migrations.CreateModel(
            name="Decharges",
            fields=[
                ("id_decharge", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "time_export_decharge_pdf",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("id_doctor", models.IntegerField(blank=True, null=True)),
                ("id_doctor_kt", models.IntegerField(blank=True, null=True)),
                ("id_employe", models.IntegerField(blank=True, null=True)),
                (
                    "id_created_par",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_created_par",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_export_par",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_export_par",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="decharges_id_export_par_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "decharges",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                ("id_payment", models.AutoField(primary_key=True, serialize=False)),
                ("payment", models.DecimalField(decimal_places=2, max_digits=10)),
                ("time_payment", models.DateTimeField(blank=True, null=True)),
                (
                    "id_decharge",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_decharge",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="payments",
                        to="finance.decharges",
                    ),
                ),
            ],
            options={
                "db_table": "Payments",
                "managed": True,
            },
        ),
    ]
