# Generated by Django 5.1.7 on 2025-08-19 19:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Decharges",
            fields=[
                ("id_decharge", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "time_export_decharge_pdf",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("id_employe", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                ("id_payment", models.AutoField(primary_key=True, serialize=False)),
                ("payment", models.DecimalField(decimal_places=2, max_digits=10)),
                ("time_payment", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="BonDePaiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "date_paiement",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "methode",
                    models.CharField(
                        choices=[
                            ("ESP", "Espèces"),
                            ("CHQ", "Chèque"),
                            ("CB", "Carte Bancaire"),
                        ],
                        default="ESP",
                        max_length=10,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=50, unique=True)),
                (
                    "encaisse_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bon de paiement",
                "verbose_name_plural": "Bons de paiement",
            },
        ),
    ]
