# Generated by Django 5.1.7 on 2025-04-22 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0001_initial"),
        ("medical", "0001_initial"),
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="id_payment_par",
            field=models.ForeignKey(
                blank=True,
                db_column="id_payment_par",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="decharges_id_payment_par_set",
                to="rh.personnel",
            ),
        ),
        migrations.AddField(
            model_name="tarif_gardes",
            name="poste",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarifs",
                to="rh.poste",
            ),
        ),
        migrations.AddField(
            model_name="tarif_gardes",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarifs",
                to="medical.service",
            ),
        ),
        migrations.AddField(
            model_name="tarif_gardes",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarifs",
                to="rh.shift",
            ),
        ),
        migrations.AddField(
            model_name="tarifacte",
            name="acte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarifs",
                to="medical.acte",
            ),
        ),
        migrations.AddField(
            model_name="tarifacteconvention",
            name="acte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarifs_convention",
                to="medical.acte",
            ),
        ),
        migrations.AddField(
            model_name="tarifacteconvention",
            name="convention",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarifs",
                to="finance.convention",
            ),
        ),
        migrations.AddField(
            model_name="tarifacteconvention",
            name="tarif_acte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarifs_par_convention",
                to="finance.tarifacte",
            ),
        ),
        migrations.AddField(
            model_name="convention",
            name="actes",
            field=models.ManyToManyField(
                related_name="conventions",
                through="finance.TarifActeConvention",
                to="medical.acte",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tarif_gardes",
            unique_together={("poste", "service", "shift")},
        ),
        migrations.AlterUniqueTogether(
            name="tarifacteconvention",
            unique_together={("convention", "acte")},
        ),
    ]
