# Generated by Django 5.1.7 on 2025-06-04 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0001_initial"),
        ("medecin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="decharges",
            name="medecin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decharges",
                to="medecin.medecin",
                verbose_name="Médecin",
            ),
        ),
    ]
