# Generated by Django 5.1.7 on 2025-08-19 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0001_initial"),
        ("medecin", "0001_initial"),
        ("medical", "0001_initial"),
        ("rh", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bondepaiement",
            name="prestation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bons_de_paiement",
                to="medical.prestationkt",
            ),
        ),
        migrations.AddField(
            model_name="decharges",
            name="id_created_par",
            field=models.ForeignKey(
                blank=True,
                db_column="id_created_par",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="decharges",
            name="id_export_par",
            field=models.ForeignKey(
                blank=True,
                db_column="id_export_par",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="decharges_id_export_par_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="decharges",
            name="medecin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decharges",
                to="medecin.medecin",
                verbose_name="Médecin",
            ),
        ),
        migrations.AddField(
            model_name="decharges",
            name="prestation_actes",
            field=models.ManyToManyField(
                related_name="decharges",
                to="medical.prestationacte",
                verbose_name="Prestations associées",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="id_decharge",
            field=models.ForeignKey(
                blank=True,
                db_column="id_decharge",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="payments",
                to="finance.decharges",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="id_payment_par",
            field=models.ForeignKey(
                blank=True,
                db_column="id_payment_par",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="decharges_id_payment_par_set",
                to="rh.personnel",
            ),
        ),
    ]
