# Generated by Django 5.1.7 on 2025-04-16 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="id_decharge",
            field=models.ForeignKey(
                blank=True,
                db_column="id_decharge",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="payments",
                to="finance.decharges",
            ),
        ),
    ]
