# Generated by Django 5.1.7 on 2025-08-10 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tarif_Gardes",
        ),
    ]
