# Generated by Django 5.1.7 on 2025-06-04 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0002_initial"),
        ("medecin", "0001_initial"),
        ("medical", "0001_initial"),
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="decharges",
            name="prestation_actes",
            field=models.ManyToManyField(
                related_name="decharges",
                to="medical.prestationacte",
                verbose_name="Prestations associées",
            ),
        ),
        migrations.AddField(
            model_name="honorairesmedecin",
            name="acte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="honoraires_medecins",
                to="medical.acte",
                verbose_name="Acte médical",
            ),
        ),
        migrations.AddField(
            model_name="honorairesmedecin",
            name="convention",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="honoraires_medecins",
                to="finance.convention",
                verbose_name="Convention appliquée",
            ),
        ),
        migrations.AddField(
            model_name="honorairesmedecin",
            name="medecin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="honoraires_configures",
                to="medecin.medecin",
                verbose_name="Médecin",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="id_decharge",
            field=models.ForeignKey(
                blank=True,
                db_column="id_decharge",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="payments",
                to="finance.decharges",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="id_payment_par",
            field=models.ForeignKey(
                blank=True,
                db_column="id_payment_par",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="decharges_id_payment_par_set",
                to="rh.personnel",
            ),
        ),
        migrations.AddField(
            model_name="tarif_gardes",
            name="poste",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarifs",
                to="rh.poste",
            ),
        ),
        migrations.AddField(
            model_name="tarif_gardes",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarifs",
                to="medical.service",
            ),
        ),
        migrations.AddField(
            model_name="tarif_gardes",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarifs",
                to="rh.shift",
            ),
        ),
        migrations.AddField(
            model_name="tarifacte",
            name="acte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarifs",
                to="medical.acte",
            ),
        ),
        migrations.AddField(
            model_name="tarifacteconvention",
            name="acte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarifs_convention",
                to="medical.acte",
            ),
        ),
        migrations.AddField(
            model_name="tarifacteconvention",
            name="convention",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarifs",
                to="finance.convention",
            ),
        ),
        migrations.AddField(
            model_name="tarifacteconvention",
            name="tarif_acte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarifs_par_convention",
                to="finance.tarifacte",
            ),
        ),
        migrations.AddField(
            model_name="convention",
            name="actes",
            field=models.ManyToManyField(
                related_name="conventions",
                through="finance.TarifActeConvention",
                to="medical.acte",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="honorairesmedecin",
            unique_together={("medecin", "acte", "convention", "date_effective")},
        ),
        migrations.AlterUniqueTogether(
            name="tarif_gardes",
            unique_together={("poste", "service", "shift")},
        ),
        migrations.AlterUniqueTogether(
            name="tarifacteconvention",
            unique_together={("convention", "acte", "date_effective")},
        ),
    ]
