# Generated by Django 5.1.7 on 2025-04-24 10:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_initial"),
        ("medecin", "0002_initial"),
        ("medical", "0006_prestationacte_honoraire_medecin"),
    ]

    operations = [
        migrations.CreateModel(
            name="HonorairesMedecin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Tarif appliqué"
                    ),
                ),
                (
                    "date_effective",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date d'effet"
                    ),
                ),
                (
                    "acte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="honoraires_medecins",
                        to="medical.acte",
                    ),
                ),
                (
                    "convention",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.convention",
                    ),
                ),
                (
                    "medecin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="honoraires_configures",
                        to="medecin.medecin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration d'honoraire médecin",
                "verbose_name_plural": "Configurations d'honoraires médecins",
                "ordering": ["-date_effective"],
                "permissions": [
                    ("manage_doctor_fees", "Peut gérer les honoraires des médecins")
                ],
                "unique_together": {
                    ("medecin", "acte", "convention", "date_effective")
                },
            },
        ),
    ]
