# Generated by Django 5.1.7 on 2025-08-22 11:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_initial"),
        ("medical", "0007_alter_prestationacte_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaiementEspecesKt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant_total_du",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant total à payer en espèces",
                        max_digits=10,
                        verbose_name="Montant total dû",
                    ),
                ),
                (
                    "montant_paye",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Somme de tous les paiements effectués",
                        max_digits=10,
                        verbose_name="Montant déjà payé",
                    ),
                ),
                (
                    "montant_restant",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant encore à payer",
                        max_digits=10,
                        verbose_name="Montant restant",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_COURS", "En cours de paiement"),
                            ("COMPLET", "Paiement complet"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="EN_COURS",
                        max_length=20,
                        verbose_name="Statut du paiement",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "date_completion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de finalisation"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notes et observations"),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paiements_especes_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "prestation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiement_especes",
                        to="medical.prestationkt",
                        verbose_name="Prestation concernée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement espèces",
                "verbose_name_plural": "Paiements espèces",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="TranchePaiementKt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Montant de cette tranche",
                    ),
                ),
                (
                    "date_paiement",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date du paiement",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, verbose_name="Notes sur cette tranche"
                    ),
                ),
                (
                    "encaisse_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tranches_encaissees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Encaissé par",
                    ),
                ),
                (
                    "paiement_especes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tranches",
                        to="finance.paiementespeceskt",
                        verbose_name="Paiement principal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tranche de paiement",
                "verbose_name_plural": "Tranches de paiement",
                "ordering": ["-date_paiement"],
            },
        ),
        migrations.DeleteModel(
            name="BonDePaiement",
        ),
        migrations.AddIndex(
            model_name="paiementespeceskt",
            index=models.Index(fields=["statut"], name="finance_pai_statut_e90c1e_idx"),
        ),
        migrations.AddIndex(
            model_name="paiementespeceskt",
            index=models.Index(
                fields=["date_creation"], name="finance_pai_date_cr_cf71c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paiementespeceskt",
            index=models.Index(
                fields=["prestation"], name="finance_pai_prestat_b6d058_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tranchepaiementkt",
            index=models.Index(
                fields=["paiement_especes"], name="finance_tra_paiemen_c040c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tranchepaiementkt",
            index=models.Index(
                fields=["date_paiement"], name="finance_tra_date_pa_bd30aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tranchepaiementkt",
            index=models.Index(
                fields=["encaisse_par"], name="finance_tra_encaiss_20b110_idx"
            ),
        ),
    ]
