# Generated by Django 5.1.7 on 2025-08-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_paiementespeceskt_tranchepaiementkt_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="decharges",
            options={
                "managed": True,
                "permissions": (
                    (
                        "create_decharge_multiple",
                        "Peut créer plusieurs décharges à la fois",
                    ),
                    ("export_decharge_pdf", "Peut exporter les décharges en PDF"),
                    ("view_situation_medecins", "Peut voir la situation des médecins"),
                    ("settle_decharge", "Peut régler une décharge"),
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="paiementespeceskt",
            options={
                "ordering": ["-date_creation"],
                "permissions": (
                    (
                        "view_paiements_especes_dashboard",
                        "Peut voir le dashboard des paiements espèces",
                    ),
                    ("export_paiements_especes", "Peut exporter les paiements espèces"),
                    (
                        "view_historique_paiements",
                        "Peut voir l'historique des paiements",
                    ),
                    ("manage_tranches_paiement", "Peut gérer les tranches de paiement"),
                ),
                "verbose_name": "Paiement espèces",
                "verbose_name_plural": "Paiements espèces",
            },
        ),
        migrations.AlterModelOptions(
            name="payments",
            options={
                "managed": True,
                "permissions": (
                    ("validate_payment", "Peut valider un paiement"),
                    ("cancel_payment", "Peut annuler un paiement"),
                    ("view_payment_history", "Peut voir l'historique des paiements"),
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="tranchepaiementkt",
            options={
                "ordering": ["-date_paiement"],
                "permissions": (
                    (
                        "annuler_tranche_paiement",
                        "Peut annuler une tranche de paiement",
                    ),
                    (
                        "modifier_tranche_paiement",
                        "Peut modifier une tranche de paiement",
                    ),
                    ("view_details_tranche", "Peut voir les détails d'une tranche"),
                ),
                "verbose_name": "Tranche de paiement",
                "verbose_name_plural": "Tranches de paiement",
            },
        ),
    ]
