# Generated by Django 5.1.7 on 2025-04-24 11:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_honorairesmedecin"),
        ("medecin", "0002_initial"),
        ("medical", "0007_prestation_honoraire_total_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="honorairesmedecin",
            name="acte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="honoraires_medecins",
                to="medical.acte",
                verbose_name="Acte médical",
            ),
        ),
        migrations.AlterField(
            model_name="honorairesmedecin",
            name="convention",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="honoraires_medecins",
                to="finance.convention",
                verbose_name="Convention appliquée",
            ),
        ),
        migrations.AlterField(
            model_name="honorairesmedecin",
            name="medecin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="honoraires_configures",
                to="medecin.medecin",
                verbose_name="Médecin",
            ),
        ),
        migrations.AlterField(
            model_name="honorairesmedecin",
            name="montant",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Montant fixe ou pourcentage à appliquer",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Tarif appliqué",
            ),
        ),
    ]
