# Generated by Django 5.1.7 on 2025-07-06 01:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_initial"),
        ("medecin", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrixSupplementaireConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pourcentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Pourcentage à appliquer sur le total des actes.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Pourcentage supplémentaire (%)",
                    ),
                ),
                (
                    "medecin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prix_supplementaire_config",
                        to="medecin.medecin",
                        verbose_name="Médecin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration Prix Supplémentaire",
                "verbose_name_plural": "Configurations Prix Supplémentaires",
            },
        ),
    ]
