# Generated by Django 5.1.7 on 2025-07-06 01:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_prixsupplementaireconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prixsupplementaireconfig",
            name="pourcentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Pourcentage à appliquer sur le prix supplémentaire par médecin.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
                verbose_name="Pourcentage supplémentaire (%)",
            ),
        ),
    ]
