# Generated by Django 5.1.7 on 2025-04-24 21:08

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_alter_honorairesmedecin_acte_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultDoctorFeePercent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=4, help_text="Ex. 0.5000 pour 50%", max_digits=5
                    ),
                ),
                ("date_effective", models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Pourcentage honoraire médecin par défaut",
                "ordering": ["-date_effective"],
            },
        ),
        migrations.AddField(
            model_name="tarifacteconvention",
            name="default_fee_percent",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.5000"),
                help_text="Pourcentage par défaut pour calculer l’honoraire si pas de tarif médecin spécifique",
                max_digits=5,
            ),
        ),
    ]
