# Generated by Django 5.1.7 on 2025-04-25 09:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_defaultdoctorfeepercent_and_more"),
        ("medical", "0012_merge_20250424_1236"),
    ]

    operations = [
        migrations.CreateModel(
            name="HonorairesBaseActeConvention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant standard de l'honoraire pour cet acte et cette convention",
                        max_digits=10,
                    ),
                ),
                ("date_effective", models.DateField(default=django.utils.timezone.now)),
                (
                    "acte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="honoraires_base",
                        to="medical.acte",
                    ),
                ),
                (
                    "convention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="honoraires_base",
                        to="finance.convention",
                    ),
                ),
            ],
            options={
                "verbose_name": "Honoraire de base acte/convention",
                "verbose_name_plural": "Honoraires de base acte/convention",
                "ordering": ["-date_effective"],
                "unique_together": {("convention", "acte", "date_effective")},
            },
        ),
        migrations.DeleteModel(
            name="DefaultDoctorFeePercent",
        ),
    ]
