# Generated by Django 5.1.7 on 2025-04-25 09:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_honorairesbaseacteconvention_and_more"),
        ("medical", "0012_merge_20250424_1236"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="honorairesmedecin",
            options={
                "ordering": ["-date_effective"],
                "verbose_name": "Configuration d'honoraire médecin",
                "verbose_name_plural": "Configurations d'honoraires médecins",
            },
        ),
        migrations.AlterUniqueTogether(
            name="tarifacteconvention",
            unique_together={("convention", "acte", "date_effective")},
        ),
        migrations.AddField(
            model_name="tarifacteconvention",
            name="montant_honoraire_base",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Montant de l'honoraire de base pour cet acte et cette convention",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="honorairesmedecin",
            name="montant",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Tarif appliqué",
            ),
        ),
        migrations.DeleteModel(
            name="HonorairesBaseActeConvention",
        ),
        migrations.RemoveField(
            model_name="tarifacteconvention",
            name="default_fee_percent",
        ),
    ]
