# Generated by Django 5.1.7 on 2025-04-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_alter_honorairesmedecin_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="honorairesmedecin",
            options={
                "ordering": ["-date_effective"],
                "verbose_name": "Config honoraire médecin",
                "verbose_name_plural": "Config honoraires médecins",
            },
        ),
        migrations.AlterModelOptions(
            name="tarifacte",
            options={
                "ordering": ["-is_default", "-date_effective"],
                "verbose_name": "Tarif de base",
                "verbose_name_plural": "Tarifs de base",
            },
        ),
        migrations.AddField(
            model_name="tarifacte",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Cocher pour ce tarif soit celui par défaut pour l’acte",
            ),
        ),
    ]
