# Generated by Django 5.1.7 on 2025-04-25 13:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_alter_honorairesmedecin_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarifacte",
            name="montant_honoraire_base",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Montant d’honoraire de base applicable hors convention",
                max_digits=10,
            ),
        ),
    ]
