# Generated by Django 5.1.7 on 2025-04-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_tarifacte_montant_honoraire_base"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="decharges",
            name="id_doctor_kt",
        ),
    ]
