# Generated by Django 5.1.7 on 2025-04-26 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_remove_decharges_id_doctor_kt"),
        ("medecin", "0003_alter_medecin_personnel"),
        ("medical", "0012_merge_20250424_1236"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="decharges",
            name="id_doctor",
        ),
        migrations.AddField(
            model_name="decharges",
            name="medecin",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decharges",
                to="medecin.medecin",
                verbose_name="Médecin",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="decharges",
            name="prestation_actes",
            field=models.ManyToManyField(
                related_name="decharges",
                to="medical.prestationacte",
                verbose_name="Prestations associées",
            ),
        ),
    ]
