# Generated by Django 5.1.7 on 2025-04-26 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0011_remove_decharges_id_doctor_decharges_medecin_and_more"),
        ("medecin", "0003_alter_medecin_personnel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decharges",
            name="medecin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decharges",
                to="medecin.medecin",
                verbose_name="Médecin",
            ),
        ),
    ]
