# Generated by Django 5.1.7 on 2025-08-09 00:59

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admission_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date d'admission",
                    ),
                ),
                (
                    "discharge_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de sortie"
                    ),
                ),
                (
                    "bed_start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Début dans ce lit",
                    ),
                ),
                (
                    "bed_end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin dans ce lit"
                    ),
                ),
                (
                    "is_current_bed",
                    models.BooleanField(default=True, verbose_name="Lit actuel"),
                ),
                ("diagnosis", models.TextField(verbose_name="Diagnostic")),
                (
                    "treatment_plan",
                    models.TextField(blank=True, verbose_name="Plan de traitement"),
                ),
                (
                    "discharge_notes",
                    models.TextField(blank=True, verbose_name="Notes de sortie"),
                ),
                (
                    "discharge_destination",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("domicile", "Domicile"),
                            ("autre_hopital", "Transfert vers autre hôpital"),
                            ("clinique", "Clinique spécialisée"),
                            ("ehpad", "EHPAD / Maison de retraite"),
                            ("centre_readaptation", "Centre de rééducation"),
                            ("soins_palliatifs", "Soins palliatifs"),
                            ("deces", "Décès"),
                            ("autre", "Autre"),
                        ],
                        max_length=30,
                        verbose_name="Destination de sortie",
                    ),
                ),
                (
                    "bed_stay_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                        verbose_name="Coût du séjour dans ce lit",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                        verbose_name="Coût total",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Admission",
                "verbose_name_plural": "Admissions",
                "ordering": ["-admission_date"],
            },
        ),
        migrations.CreateModel(
            name="AdmissionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "En attente"),
                            ("approved", "Approuvé"),
                            ("admitted", "Admis"),
                            ("cancelled", "Annulé"),
                            ("transferred", "Transféré"),
                        ],
                        default="waiting",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Motif d'admission")),
                (
                    "diagnosis",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Diagnostic préliminaire",
                    ),
                ),
                (
                    "request_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de demande",
                    ),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Durée estimée (jours)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Demande d'admission",
                "verbose_name_plural": "Demandes d'admission",
                "ordering": ["-request_date"],
            },
        ),
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bed_number",
                    models.CharField(max_length=10, verbose_name="Numéro de lit"),
                ),
                (
                    "is_occupied",
                    models.BooleanField(default=False, verbose_name="Occupé"),
                ),
                (
                    "bed_type",
                    models.CharField(
                        choices=[
                            ("standard", "Lit Standard"),
                            ("electrique", "Lit Électrique"),
                            ("isolation", "Lit d'Isolation"),
                            ("pediatrique", "Lit Pédiatrique"),
                            ("geriatrique", "Lit Gériatrique"),
                            ("reanimation", "Lit de Réanimation"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="Type de lit",
                    ),
                ),
                (
                    "bed_equipment",
                    models.TextField(
                        blank=True,
                        help_text="Équipements spéciaux associés à ce lit",
                        null=True,
                        verbose_name="Équipements du lit",
                    ),
                ),
                (
                    "equipment_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes particulières sur les équipements",
                        null=True,
                        verbose_name="Notes sur les équipements",
                    ),
                ),
                (
                    "maintenance_required",
                    models.BooleanField(
                        default=False,
                        help_text="Indique si le lit nécessite une maintenance",
                        verbose_name="Maintenance requise",
                    ),
                ),
                (
                    "special_requirements",
                    models.TextField(
                        blank=True,
                        help_text="Exigences particulières pour ce lit",
                        null=True,
                        verbose_name="Exigences spéciales",
                    ),
                ),
                (
                    "last_cleaned",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière désinfection"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lit",
                "verbose_name_plural": "Lits",
                "ordering": ["room", "bed_number"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_number",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Numéro de chambre"
                    ),
                ),
                ("floor", models.IntegerField(default=1, verbose_name="Étage")),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("single", "Chambre individuelle"),
                            ("double", "Chambre double"),
                            ("triple", "Chambre triple"),
                            ("quad", "Chambre quadruple"),
                            ("vip", "Chambre VIP"),
                            ("soins_intensifs", "Soins Intensifs"),
                            ("pediatrie", "Chambre Pédiatrie"),
                        ],
                        default="double",
                        max_length=20,
                        verbose_name="Type de chambre",
                    ),
                ),
                (
                    "bed_capacity",
                    models.IntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Nombre de lits",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "night_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15000.00"),
                        help_text="Prix facturé par nuit de séjour",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Prix par nuitée (DA)",
                    ),
                ),
                (
                    "maintenance_required",
                    models.BooleanField(
                        default=False,
                        help_text="Indique si la chambre nécessite une maintenance",
                        verbose_name="Maintenance requise",
                    ),
                ),
                (
                    "room_equipment",
                    models.TextField(
                        blank=True,
                        help_text="Liste des équipements disponibles dans la chambre",
                        null=True,
                        verbose_name="Équipements de la chambre",
                    ),
                ),
                (
                    "special_requirements",
                    models.TextField(
                        blank=True,
                        help_text="Exigences particulières pour cette chambre",
                        null=True,
                        verbose_name="Exigences spéciales",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chambre",
                "verbose_name_plural": "Chambres",
                "ordering": ["service", "floor", "room_number"],
            },
        ),
        migrations.CreateModel(
            name="StayHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Date début")),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date fin"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Coût",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Historique de séjour",
                "verbose_name_plural": "Historiques de séjour",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transfer_date", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TransferHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transfer_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de transfert",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, verbose_name="Motif du transfert"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Historique de transfert",
                "verbose_name_plural": "Historiques de transferts",
                "ordering": ["-transfer_date"],
            },
        ),
    ]
