# Generated by Django 5.1.7 on 2025-08-19 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hospitalisations", "0001_initial"),
        ("medecin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="attending_doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="medecin.medecin",
                verbose_name="Médecin traitant",
            ),
        ),
    ]
