# Generated by Django 5.1.7 on 2025-08-19 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hospitalisations", "0002_initial"),
        ("medecin", "0002_initial"),
        ("medical", "0001_initial"),
        ("patients", "0001_initial"),
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rh.personnel",
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="parent_admission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bed_stays",
                to="hospitalisations.admission",
                verbose_name="Admission principale",
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admissions",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AddField(
            model_name="admissionrequest",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_admission_requests",
                to="rh.personnel",
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="admissionrequest",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admission_requests",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AddField(
            model_name="admissionrequest",
            name="referring_doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to="medecin.medecin",
                verbose_name="Médecin référent",
            ),
        ),
        migrations.AddField(
            model_name="admissionrequest",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="admission_requests",
                to="medical.service",
                verbose_name="Service demandé",
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="admission_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admissions",
                to="hospitalisations.admissionrequest",
                verbose_name="Demande d'admission",
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="bed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admissions",
                to="hospitalisations.bed",
                verbose_name="Lit",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rooms",
                to="medical.service",
                verbose_name="Service",
            ),
        ),
        migrations.AddField(
            model_name="bed",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beds",
                to="hospitalisations.room",
                verbose_name="Chambre",
            ),
        ),
        migrations.AddField(
            model_name="stayhistory",
            name="admission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stay_details",
                to="hospitalisations.admission",
                verbose_name="Admission",
            ),
        ),
        migrations.AddField(
            model_name="stayhistory",
            name="bed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hospitalisations.bed",
                verbose_name="Lit",
            ),
        ),
        migrations.AddField(
            model_name="stayhistory",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stay_histories",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="Transfer_admission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers_admission",
                to="hospitalisations.admission",
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="Transfer_from_bed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers_from_lit",
                to="hospitalisations.bed",
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="Transfer_to_bed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers_to_lit",
                to="hospitalisations.bed",
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rh.personnel",
            ),
        ),
        migrations.AddField(
            model_name="transferhistory",
            name="admission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers",
                to="hospitalisations.admission",
                verbose_name="Admission",
            ),
        ),
        migrations.AddField(
            model_name="transferhistory",
            name="from_bed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers_from",
                to="hospitalisations.bed",
                verbose_name="Lit d'origine",
            ),
        ),
        migrations.AddField(
            model_name="transferhistory",
            name="to_bed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers_to",
                to="hospitalisations.bed",
                verbose_name="Lit de destination",
            ),
        ),
        migrations.AddField(
            model_name="transferhistory",
            name="transferred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rh.personnel",
                verbose_name="Transféré par",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("service", "room_number")},
        ),
        migrations.AlterUniqueTogether(
            name="bed",
            unique_together={("room", "bed_number")},
        ),
    ]
