# Generated by Django 5.1.7 on 2025-08-24 20:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitalisations", "0003_initial"),
        ("medecin", "0002_initial"),
        ("medical", "0010_alter_convention_options_alter_prestationkt_options"),
        ("patients", "0002_import_patients"),
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "mis_a_jour_le",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "numero_lit",
                    models.CharField(max_length=10, verbose_name="Numéro de lit"),
                ),
                (
                    "est_occupe",
                    models.BooleanField(default=False, verbose_name="Occupé"),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Lit",
                "verbose_name_plural": "Lits",
                "ordering": ["chambre", "numero_lit"],
            },
        ),
        migrations.CreateModel(
            name="Transfert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_transfert",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de transfert",
                    ),
                ),
                (
                    "motif",
                    models.TextField(blank=True, verbose_name="Motif du transfert"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("mis_a_jour_le", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Transfert",
                "verbose_name_plural": "Transferts",
                "ordering": ["-date_transfert"],
            },
        ),
        migrations.RemoveField(
            model_name="admissionrequest",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="admissionrequest",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="admissionrequest",
            name="referring_doctor",
        ),
        migrations.RemoveField(
            model_name="admissionrequest",
            name="service",
        ),
        migrations.RemoveField(
            model_name="admission",
            name="admission_request",
        ),
        migrations.AlterUniqueTogether(
            name="bed",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="bed",
            name="room",
        ),
        migrations.RemoveField(
            model_name="admission",
            name="bed",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="Transfer_to_bed",
        ),
        migrations.RemoveField(
            model_name="transferhistory",
            name="from_bed",
        ),
        migrations.RemoveField(
            model_name="transferhistory",
            name="to_bed",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="Transfer_from_bed",
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="room",
            name="service",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="Transfer_admission",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="transferhistory",
            name="admission",
        ),
        migrations.RemoveField(
            model_name="transferhistory",
            name="transferred_by",
        ),
        migrations.AlterModelOptions(
            name="admission",
            options={
                "ordering": ["-date_admission"],
                "verbose_name": "Admission",
                "verbose_name_plural": "Admissions",
            },
        ),
        migrations.RenameField(
            model_name="admission",
            old_name="admission_date",
            new_name="date_admission",
        ),
        migrations.RenameField(
            model_name="admission",
            old_name="discharge_date",
            new_name="date_sortie",
        ),
        migrations.RenameField(
            model_name="admission",
            old_name="is_active",
            new_name="est_active",
        ),
        migrations.RenameField(
            model_name="admission",
            old_name="attending_doctor",
            new_name="medecin_traitant",
        ),
        migrations.RenameField(
            model_name="admission",
            old_name="discharge_notes",
            new_name="notes_sortie",
        ),
        migrations.RemoveField(
            model_name="admission",
            name="bed_end_date",
        ),
        migrations.RemoveField(
            model_name="admission",
            name="bed_start_date",
        ),
        migrations.RemoveField(
            model_name="admission",
            name="bed_stay_cost",
        ),
        migrations.RemoveField(
            model_name="admission",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="admission",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="admission",
            name="diagnosis",
        ),
        migrations.RemoveField(
            model_name="admission",
            name="discharge_destination",
        ),
        migrations.RemoveField(
            model_name="admission",
            name="is_current_bed",
        ),
        migrations.RemoveField(
            model_name="admission",
            name="parent_admission",
        ),
        migrations.RemoveField(
            model_name="admission",
            name="total_cost",
        ),
        migrations.RemoveField(
            model_name="admission",
            name="treatment_plan",
        ),
        migrations.RemoveField(
            model_name="admission",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="admission",
            name="cout_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Coût total",
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="cree_le",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Créé le",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="admission",
            name="cree_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_crees",
                to="rh.personnel",
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="mis_a_jour_le",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AddField(
            model_name="admission",
            name="mis_a_jour_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_mis_a_jour",
                to="rh.personnel",
                verbose_name="Mis à jour par",
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="statut",
            field=models.CharField(
                choices=[
                    ("active", "Actif"),
                    ("discharged", "Sorti"),
                    ("cancelled", "Annulé"),
                ],
                default="active",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AddField(
            model_name="stayhistory",
            name="cree_le",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Créé le",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stayhistory",
            name="cree_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_crees",
                to="rh.personnel",
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="stayhistory",
            name="mis_a_jour_le",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AddField(
            model_name="stayhistory",
            name="mis_a_jour_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_mis_a_jour",
                to="rh.personnel",
                verbose_name="Mis à jour par",
            ),
        ),
        migrations.AlterField(
            model_name="stayhistory",
            name="admission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historique_sejours",
                to="hospitalisations.admission",
            ),
        ),
        migrations.AlterField(
            model_name="stayhistory",
            name="cost",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="stayhistory",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="stayhistory",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historique_sejours",
                to="patients.patient",
            ),
        ),
        migrations.CreateModel(
            name="AttributionLit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_debut",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date de début"
                    ),
                ),
                (
                    "date_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de fin"
                    ),
                ),
                (
                    "cout",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        null=True,
                        verbose_name="Coût du séjour dans ce lit",
                    ),
                ),
                (
                    "est_courante",
                    models.BooleanField(
                        default=True, verbose_name="Attribution courante"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("mis_a_jour_le", models.DateTimeField(auto_now=True)),
                (
                    "admission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributions_lits",
                        to="hospitalisations.admission",
                        verbose_name="Admission",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attributions_crees",
                        to="rh.personnel",
                    ),
                ),
                (
                    "mis_a_jour_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attributions_mis_a_jour",
                        to="rh.personnel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attribution de lit",
                "verbose_name_plural": "Attributions de lits",
                "ordering": ["date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Chambre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "mis_a_jour_le",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "numero_chambre",
                    models.CharField(max_length=10, verbose_name="Numéro de chambre"),
                ),
                (
                    "type_chambre",
                    models.CharField(
                        choices=[
                            ("single", "Chambre individuelle"),
                            ("double", "Chambre double"),
                            ("triple", "Chambre triple"),
                            ("quad", "Chambre quadruple"),
                            ("vip", "Chambre VIP"),
                            ("soins_intensifs", "Soins Intensifs"),
                            ("pediatrie", "Chambre Pédiatrie"),
                        ],
                        default="double",
                        max_length=20,
                        verbose_name="Type de chambre",
                    ),
                ),
                (
                    "capacite_lits",
                    models.PositiveSmallIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name="Nombre de lits",
                    ),
                ),
                (
                    "prix_nuit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15000.00"),
                        help_text="Prix facturé par nuit de séjour",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Prix par nuitée (DA)",
                    ),
                ),
                ("est_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_crees",
                        to="rh.personnel",
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "mis_a_jour_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_mis_a_jour",
                        to="rh.personnel",
                        verbose_name="Mis à jour par",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chambres",
                        to="medical.service",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chambre",
                "verbose_name_plural": "Chambres",
                "ordering": ["service__name", "numero_chambre"],
            },
        ),
        migrations.CreateModel(
            name="DemandeAdmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "mis_a_jour_le",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("waiting", "En attente"),
                            ("admitted", "Admis"),
                            ("cancelled", "Annulé"),
                            ("transferred", "Transféré"),
                        ],
                        default="waiting",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "motif",
                    models.TextField(blank=True, verbose_name="Motif d'admission"),
                ),
                (
                    "date_demande",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de demande",
                    ),
                ),
                (
                    "duree_estimee",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Durée estimée (jours)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_crees",
                        to="rh.personnel",
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "medecin_referent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="references",
                        to="medecin.medecin",
                        verbose_name="Médecin référent",
                    ),
                ),
                (
                    "mis_a_jour_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_mis_a_jour",
                        to="rh.personnel",
                        verbose_name="Mis à jour par",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes_admissions",
                        to="patients.patient",
                        verbose_name="Patient",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandes_admissions",
                        to="medical.service",
                        verbose_name="Service demandé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande d'admission",
                "verbose_name_plural": "Demandes d'admission",
                "ordering": ["-date_demande"],
            },
        ),
        migrations.AddField(
            model_name="admission",
            name="demande_admission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admissions",
                to="hospitalisations.demandeadmission",
                verbose_name="Demande d'admission",
            ),
        ),
        migrations.AddIndex(
            model_name="admission",
            index=models.Index(
                fields=["patient", "statut"], name="hospitalisa_patient_1cb1f0_idx"
            ),
        ),
        migrations.AddField(
            model_name="lit",
            name="chambre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lits",
                to="hospitalisations.chambre",
                verbose_name="Chambre",
            ),
        ),
        migrations.AddField(
            model_name="lit",
            name="cree_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_crees",
                to="rh.personnel",
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="lit",
            name="mis_a_jour_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_mis_a_jour",
                to="rh.personnel",
                verbose_name="Mis à jour par",
            ),
        ),
        migrations.AddField(
            model_name="attributionlit",
            name="lit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attributions_lits",
                to="hospitalisations.lit",
                verbose_name="Lit",
            ),
        ),
        migrations.AlterField(
            model_name="stayhistory",
            name="bed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hospitalisations.lit"
            ),
        ),
        migrations.AddField(
            model_name="transfert",
            name="admission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transferts",
                to="hospitalisations.admission",
                verbose_name="Admission",
            ),
        ),
        migrations.AddField(
            model_name="transfert",
            name="cree_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transferts_crees",
                to="rh.personnel",
            ),
        ),
        migrations.AddField(
            model_name="transfert",
            name="from_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfer_from",
                to="hospitalisations.attributionlit",
            ),
        ),
        migrations.AddField(
            model_name="transfert",
            name="mis_a_jour_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transferts_mis_a_jour",
                to="rh.personnel",
            ),
        ),
        migrations.AddField(
            model_name="transfert",
            name="to_assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfer_to",
                to="hospitalisations.attributionlit",
            ),
        ),
        migrations.AddField(
            model_name="transfert",
            name="transfere_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rh.personnel",
                verbose_name="Transféré par",
            ),
        ),
        migrations.DeleteModel(
            name="AdmissionRequest",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
        migrations.DeleteModel(
            name="Transfer",
        ),
        migrations.DeleteModel(
            name="TransferHistory",
        ),
        migrations.AddIndex(
            model_name="chambre",
            index=models.Index(
                fields=["service"], name="hospitalisa_service_a4eb37_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chambre",
            unique_together={("service", "numero_chambre")},
        ),
        migrations.AddIndex(
            model_name="demandeadmission",
            index=models.Index(fields=["statut"], name="hospitalisa_statut_98321e_idx"),
        ),
        migrations.AddIndex(
            model_name="lit",
            index=models.Index(
                fields=["chambre", "est_occupe"], name="hospitalisa_chambre_e604c6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lit",
            unique_together={("chambre", "numero_lit")},
        ),
        migrations.AddIndex(
            model_name="attributionlit",
            index=models.Index(
                fields=["admission", "est_courante"],
                name="hospitalisa_admissi_4795e7_idx",
            ),
        ),
        migrations.DeleteModel(
            name="Bed",
        ),
        migrations.AddIndex(
            model_name="transfert",
            index=models.Index(
                fields=["admission", "date_transfert"],
                name="hospitalisa_admissi_fd4084_idx",
            ),
        ),
    ]
