# Generated by Django 5.1.7 on 2025-08-24 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "hospitalisations",
            "0004_lit_transfert_remove_admissionrequest_created_by_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="lit",
            old_name="est_actif",
            new_name="est_active",
        ),
    ]
