# Generated by Django 5.1.7 on 2025-08-24 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitalisations", "0005_rename_est_actif_lit_est_active"),
        ("medical", "0011_rename_est_actif_actelocation_est_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfert",
            name="from_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transferts_depuis",
                to="medical.service",
                verbose_name="Service source",
            ),
        ),
        migrations.AddField(
            model_name="transfert",
            name="to_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transferts_vers",
                to="medical.service",
                verbose_name="Service destination",
            ),
        ),
        migrations.AlterField(
            model_name="transfert",
            name="to_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfer_to",
                to="hospitalisations.attributionlit",
            ),
        ),
    ]
