# Generated by Django 5.1.7 on 2025-08-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hospitalisations",
            "0006_transfert_from_service_transfert_to_service_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission",
            name="statut",
            field=models.CharField(
                choices=[
                    ("active", "Actif"),
                    ("discharged", "Sorti"),
                    ("transferred", "Transféré"),
                    ("cancelled", "Annulé"),
                ],
                default="active",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
