# Generated by Django 5.1.7 on 2025-08-26 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitalisations", "0007_alter_admission_statut"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandeadmission",
            name="admission_source",
            field=models.ForeignKey(
                blank=True,
                help_text="Rempli uniquement pour les demandes issues d'un transfert inter-services",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="demandes_transfert",
                to="hospitalisations.admission",
                verbose_name="Admission source (pour transferts)",
            ),
        ),
    ]
