# Generated by Django 5.1.7 on 2025-08-27 00:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitalisations", "0008_demandeadmission_admission_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributionlit",
            name="prix_nuit_applique",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Prix de la chambre au moment de l'attribution (fixé pour cette période)",
                max_digits=10,
                null=True,
                verbose_name="Prix/nuit appliqué",
            ),
        ),
        migrations.AddField(
            model_name="stayhistory",
            name="prix_nuit_periode",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Prix/nuit durant cette période",
            ),
        ),
        migrations.AlterField(
            model_name="chambre",
            name="prix_nuit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("15000.00"),
                help_text="Prix facturé par nuit de séjour (24h)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Prix par nuitée (DA)",
            ),
        ),
        migrations.AlterField(
            model_name="demandeadmission",
            name="admission_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="demandes_transfert",
                to="hospitalisations.admission",
                verbose_name="Admission source (pour transferts)",
            ),
        ),
    ]
