# Generated by Django 5.1.7 on 2025-08-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitalisations", "0009_attributionlit_prix_nuit_applique_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributionlit",
            name="seuil_sejour_court",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Seuil en heures fixé au moment de l'attribution",
                null=True,
                verbose_name="Seuil séjour court (heures)",
            ),
        ),
        migrations.AddField(
            model_name="attributionlit",
            name="tarif_fixe_service",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Tarif fixe du service au moment de l'attribution (pour séjours courts)",
                max_digits=10,
                null=True,
                verbose_name="Tarif fixe du service",
            ),
        ),
        migrations.AlterField(
            model_name="attributionlit",
            name="prix_nuit_applique",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Prix de la chambre au moment de l'attribution",
                max_digits=10,
                null=True,
                verbose_name="Prix/nuit appliqué",
            ),
        ),
    ]
