# Generated by Django 5.1.7 on 2025-06-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Helpdesk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("details", models.TextField()),
                ("file_path", models.CharField(blank=True, max_length=1000, null=True)),
                ("audio_path", models.CharField(blank=True, max_length=255, null=True)),
                ("time_send", models.DateTimeField(blank=True, null=True)),
                ("time_terminee", models.DateField(blank=True, null=True)),
                (
                    "terminee_par",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "permissions": (
                    ("ACCES_AU_DEPARTEMENT_IT", "Accès au département IT"),
                    (
                        "ACCES_AU_DEPARTEMENT_TECHNIQUE",
                        "Accès au département Technique",
                    ),
                    (
                        "ACCES_AU_DEPARTEMENT_APPROVISIONNEMENT",
                        "Accès au département Approvisionnement",
                    ),
                ),
                "managed": True,
            },
        ),
    ]
