# Generated by Django 5.1.7 on 2025-04-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("helpdesk", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="helpdesk",
            options={
                "managed": True,
                "permissions": (
                    ("ACCES_AU_DEPARTEMENT_IT", "Accès au département IT"),
                    (
                        "ACCES_AU_DEPARTEMENT_TECHNIQUE",
                        "Accès au département Technique",
                    ),
                    (
                        "ACCES_AU_DEPARTEMENT_APPROVISIONNEMENT",
                        "Accès au département Approvisionnement",
                    ),
                ),
            },
        ),
    ]
