# Generated by Django 5.1.7 on 2025-06-08 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exported_models",
                    models.TextField(help_text="Modèles exportés (JSON)"),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[("csv", "CSV"), ("excel", "Excel"), ("json", "JSON")],
                        max_length=10,
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("records_count", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique d'export",
                "verbose_name_plural": "Historiques d'exports",
                "ordering": ["-created_at"],
            },
        ),
    ]
