# Generated by Django 5.1.7 on 2025-04-09 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                ("id_service", models.AutoField(primary_key=True, serialize=False)),
                ("service_name", models.CharField(max_length=255)),
                (
                    "prix_joure",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "prix_nuit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "prix_24h",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salaire",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                "db_table": "services",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Personnel",
            fields=[
                ("id_personnel", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(blank=True, max_length=100, null=True)),
                ("prenom", models.CharField(blank=True, max_length=100, null=True)),
                ("role", models.CharField(blank=True, max_length=50, null=True)),
                ("telephone", models.CharField(blank=True, max_length=15, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("statut_activite", models.BooleanField(default=True)),
                ("use_in_planning", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personnels",
                        to="rh.services",
                    ),
                ),
            ],
            options={
                "db_table": "personnel",
                "ordering": ["prenom"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Planning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shift_date", models.DateField()),
                ("shift_type", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "prix",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "prix_acte",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "paiement",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("pointage_created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rh.personnel",
                    ),
                ),
                (
                    "id_created_par",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_created_par",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="id_created_par",
                        to="rh.personnel",
                    ),
                ),
                (
                    "pointage_id_created_par",
                    models.ForeignKey(
                        blank=True,
                        db_column="pointage_id_created_par",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="pointage_id_created_par",
                        to="rh.personnel",
                    ),
                ),
                (
                    "id_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="rh.services"
                    ),
                ),
            ],
            options={
                "db_table": "planning",
                "permissions": (
                    ("acces_aux_plannings", "Accès aux plannings"),
                    ("creer_planning", "Créer un planning"),
                    ("modifier_planning", "Modifier un planning"),
                    ("supprimer_planning", "Supprimer un planning"),
                    ("exporter_planning", "Exporter un planning"),
                ),
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="HonorairesActe",
            fields=[
                ("id_acte", models.AutoField(primary_key=True, serialize=False)),
                ("name_acte", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "prix_acte",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=10, null=True
                    ),
                ),
                (
                    "id_service",
                    models.ForeignKey(
                        db_column="id_service",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rh.services",
                    ),
                ),
            ],
            options={
                "db_table": "honoraires_acte",
                "managed": True,
            },
        ),
    ]
