# Generated by Django 5.1.7 on 2025-04-15 20:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnvizConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Nom"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        protocol="IPv4", verbose_name="Adresse IP"
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=100, verbose_name="Nom d'utilisateur"),
                ),
                (
                    "password",
                    models.CharField(max_length=100, verbose_name="Mot de passe"),
                ),
                (
                    "session_timeout",
                    models.PositiveIntegerField(
                        default=1800, verbose_name="Délai de session (secondes)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration Pointeuse",
                "verbose_name_plural": "Configuration Pointeuse",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anviz_id",
                    models.BigIntegerField(unique=True, verbose_name="ID Anviz"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom complet")),
                (
                    "card_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Numéro de badge",
                    ),
                ),
                (
                    "department",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Département"
                    ),
                ),
                (
                    "group",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Groupe"),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[("day", "Jour"), ("night", "Nuit"), ("24h", "24h")],
                        default="day",
                        max_length=5,
                        verbose_name="Type de shift",
                    ),
                ),
                (
                    "reference_start",
                    models.TimeField(
                        blank=True,
                        null=True,
                        verbose_name="Heure de début de référence",
                    ),
                ),
                (
                    "reference_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de fin de référence"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Employé",
                "verbose_name_plural": "Employés",
            },
        ),
        migrations.CreateModel(
            name="HonorairesActe",
            fields=[
                ("id_acte", models.AutoField(primary_key=True, serialize=False)),
                ("name_acte", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "prix_acte",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "db_table": "honoraires_acte",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                ("id_service", models.AutoField(primary_key=True, serialize=False)),
                ("service_name", models.CharField(max_length=255)),
                (
                    "prix_joure",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "prix_nuit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "prix_24h",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salaire",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                "db_table": "services",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Personnel",
            fields=[
                ("id_personnel", models.AutoField(primary_key=True, serialize=False)),
                ("nom_prenom", models.CharField(blank=True, max_length=100, null=True)),
                ("role", models.CharField(blank=True, max_length=50, null=True)),
                ("telephone", models.CharField(blank=True, max_length=15, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("statut_activite", models.BooleanField(default=True)),
                ("use_in_planning", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personnels",
                        to="rh.services",
                    ),
                ),
            ],
            options={
                "db_table": "personnel",
                "ordering": ["nom_prenom"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("VAC", "Congé annuel"),
                            ("SIC", "Congé maladie"),
                            ("MAT", "Congé maternité"),
                            ("PAT", "Congé paternité"),
                            ("AUT", "Autre"),
                        ],
                        default="VAC",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PEN", "En attente"),
                            ("APP", "Approuvé"),
                            ("REJ", "Rejeté"),
                            ("CAN", "Annulé"),
                        ],
                        default="PEN",
                        max_length=3,
                    ),
                ),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="rh.personnel",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("process_leave_request", "Peut traiter les demandes de congé")
                ],
            },
        ),
        migrations.CreateModel(
            name="Planning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shift_date", models.DateField()),
                ("shift_type", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "prix",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "prix_acte",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "paiement",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("pointage_created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rh.personnel",
                    ),
                ),
                (
                    "id_created_par",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_created_par",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="id_created_par",
                        to="rh.personnel",
                    ),
                ),
                (
                    "pointage_id_created_par",
                    models.ForeignKey(
                        blank=True,
                        db_column="pointage_id_created_par",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="pointage_id_created_par",
                        to="rh.personnel",
                    ),
                ),
                (
                    "id_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="rh.services"
                    ),
                ),
            ],
            options={
                "db_table": "planning",
                "permissions": (
                    ("acces_aux_plannings", "Accès aux plannings"),
                    ("creer_planning", "Créer un planning"),
                    ("modifier_planning", "Modifier un planning"),
                    ("supprimer_planning", "Supprimer un planning"),
                    ("exporter_planning", "Exporter un planning"),
                ),
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PointagesActes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nbr_actes", models.IntegerField()),
                (
                    "id_acte",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_acte",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rh.honorairesacte",
                    ),
                ),
                (
                    "id_planning",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_planning",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rh.planning",
                    ),
                ),
            ],
            options={
                "db_table": "pointages_actes",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SalaryAdvanceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("request_date", models.DateField(default=django.utils.timezone.now)),
                ("payment_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PEN", "En attente"),
                            ("APP", "Approuvée"),
                            ("REJ", "Rejetée"),
                            ("CAN", "Annulée"),
                        ],
                        default="PEN",
                        max_length=3,
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_advances",
                        to="rh.personnel",
                    ),
                ),
            ],
            options={
                "permissions": [
                    (
                        "process_salaryadvance_request",
                        "Peut traiter les demandes d'avance sur salaire",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="honorairesacte",
            name="id_service",
            field=models.ForeignKey(
                db_column="id_service",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="rh.services",
            ),
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_time", models.DateTimeField(verbose_name="Heure de pointage")),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("IN", "Entrée"),
                            ("OUT", "Sortie"),
                            ("2", "Début pause"),
                            ("3", "Fin pause"),
                            ("4", "Heure supplémentaire"),
                            ("5", "Retard"),
                            ("6", "Absence"),
                        ],
                        max_length=6,
                        verbose_name="Type de pointage",
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de synchronisation"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="rh.employee",
                        verbose_name="Employé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pointage",
                "verbose_name_plural": "Pointages",
                "indexes": [
                    models.Index(
                        fields=["check_time"], name="rh_attendan_check_t_0de09e_idx"
                    ),
                    models.Index(
                        fields=["employee", "check_time"],
                        name="rh_attendan_employe_989d3f_idx",
                    ),
                ],
                "unique_together": {("employee", "check_time")},
            },
        ),
    ]
