# Generated by Django 5.1.7 on 2025-08-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_initial"),
        ("medical", "0002_initial"),
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="planning",
            constraint=models.UniqueConstraint(
                fields=("employee", "shift_date"),
                name="unique_employee_per_date",
                violation_error_message="Cet employé est déjà planifié pour cette date.",
            ),
        ),
    ]
