# Generated by Django 5.1.7 on 2025-05-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnel",
            name="salaire",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Salaire mensuel",
            ),
        ),
    ]
