# Generated by Django 5.1.7 on 2025-04-16 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="planning",
            name="decharge_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="planning",
            name="id_decharge_par",
            field=models.ForeignKey(
                blank=True,
                db_column="id_decharge_par",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="id_decharge_par",
                to="rh.personnel",
            ),
        ),
        migrations.AlterField(
            model_name="planning",
            name="paiement",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="planning",
            name="prix",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="planning",
            name="prix_acte",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
