# Generated by Django 5.1.7 on 2025-04-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personnel",
            name="use_in_planning",
            field=models.BooleanField(default=False),
        ),
    ]
