# Generated by Django 5.1.7 on 2025-04-21 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0002_alter_personnel_use_in_planning"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personnel",
            name="role",
        ),
    ]
