# Generated by Django 5.1.7 on 2025-08-10 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0002_initial"),
        ("rh", "0002_planning_unique_employee_per_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tarif_Gardes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prix",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Prix (€)",
                    ),
                ),
                (
                    "salaire",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Salaire (€)",
                    ),
                ),
                (
                    "poste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifs",
                        to="rh.poste",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifs",
                        to="medical.service",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifs",
                        to="rh.shift",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarif_Gardes",
                "verbose_name_plural": "Tarif_Gardes",
                "unique_together": {("poste", "service", "shift")},
            },
        ),
    ]
