# Generated by Django 5.1.7 on 2025-04-16 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0002_planning_decharge_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="planning",
            old_name="id_decharge_par",
            new_name="decharge_id_created_par",
        ),
    ]
