# Generated by Django 5.1.7 on 2025-04-03 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0002_alter_personnel_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="planning",
            options={
                "managed": True,
                "permissions": (
                    ("creer_planning", "Créer un planning"),
                    ("modifier_planning", "Modifier un planning"),
                    ("supprimer_planning", "Supprimer un planning"),
                    ("exporter_planning", "Exporter un planning"),
                ),
            },
        ),
    ]
