# Generated by Django 5.1.7 on 2025-05-07 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0002_personnel_salaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnel",
            name="employee",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personnel",
                to="rh.employee",
                verbose_name="Fiche Pointeuse",
            ),
        ),
    ]
