# Generated by Django 5.1.7 on 2025-05-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0003_personnel_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
            ],
            options={
                "verbose_name": "Jour férié",
                "verbose_name_plural": "Jours fériés",
            },
        ),
    ]
