# Generated by Django 5.1.7 on 2025-04-21 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0002_initial"),
        ("rh", "0003_remove_personnel_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personnel",
            name="id_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personnels",
                to="medical.services",
            ),
        ),
    ]
