# Generated by Django 5.1.7 on 2025-04-04 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0003_alter_planning_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personnel",
            name="id_service",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personnels",
                to="rh.services",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="planning",
            name="id_service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rh.services"
            ),
        ),
    ]
