# Generated by Django 5.1.7 on 2025-05-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0003_personnel_employee"),
    ]

    operations = [

    ]
