# Generated by Django 5.1.7 on 2025-06-18 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0004_publicholiday"),
    ]

    operations = [

    ]
