# Generated by Django 5.1.7 on 2025-04-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0004_alter_personnel_id_service_alter_planning_id_service"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="planning",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="planning",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
