# Generated by Django 5.1.7 on 2025-04-21 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0004_alter_personnel_id_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poste",
            name="code",
        ),
    ]
