# Generated by Django 5.1.7 on 2025-05-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0004_publicholiday"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "verbose_name": "Employé (Pointeuse)",
                "verbose_name_plural": "Employés (Pointeuse)",
            },
        ),
    ]
