# Generated by Django 5.1.7 on 2025-04-21 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0005_remove_poste_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pointagesactes",
            name="id_planning",
            field=models.ForeignKey(
                blank=True,
                db_column="id_planning",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rh.planning",
            ),
        ),
    ]
