# Generated by Django 5.1.7 on 2025-04-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0005_alter_planning_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="planning",
            options={
                "managed": True,
                "permissions": (
                    ("acces_aux_plannings", "Accès aux plannings"),
                    ("creer_planning", "Créer un planning"),
                    ("modifier_planning", "Modifier un planning"),
                    ("supprimer_planning", "Supprimer un planning"),
                    ("exporter_planning", "Exporter un planning"),
                ),
            },
        ),
    ]
