# Generated by Django 5.1.7 on 2025-05-09 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0005_alter_employee_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PublicHoliday",
            new_name="JourFerie",
        ),
        migrations.RenameModel(
            old_name="Attendance",
            new_name="Pointage",
        ),
        migrations.RenameIndex(
            model_name="pointage",
            new_name="rh_pointage_check_t_a3785c_idx",
            old_name="rh_attendan_check_t_0de09e_idx",
        ),
        migrations.RenameIndex(
            model_name="pointage",
            new_name="rh_pointage_employe_464a2d_idx",
            old_name="rh_attendan_employe_989d3f_idx",
        ),
    ]
