# Generated by Django 5.1.7 on 2025-05-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0006_rename_publicholiday_jourferie_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointage",
            name="is_validated",
            field=models.BooleanField(default=True, verbose_name="Validé"),
        ),
    ]
