# Generated by Django 5.1.7 on 2025-04-21 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_initial"),
        ("rh", "0006_alter_pointagesactes_id_planning"),
    ]

    operations = [
        migrations.AddField(
            model_name="planning",
            name="id_decharge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plannings",
                to="finance.decharges",
            ),
        ),
    ]
