# Generated by Django 5.1.7 on 2025-04-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0006_alter_planning_options"),
    ]

    operations = []
