# Generated by Django 5.1.7 on 2025-04-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0007_auto_20250406_1407"),
    ]

    operations = []
