# Generated by Django 5.1.7 on 2025-05-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0007_pointage_is_validated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pointage",
            name="check_type",
        ),
    ]
