# Generated by Django 5.1.7 on 2025-04-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0007_planning_id_decharge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planning",
            name="decharge_created_at",
        ),
        migrations.RemoveField(
            model_name="planning",
            name="decharge_id_created_par",
        ),
    ]
