# Generated by Django 5.1.7 on 2025-04-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0008_auto_20250407_1042"),
    ]

    operations = []
