# Generated by Django 5.1.7 on 2025-05-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0008_remove_pointage_check_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="card_number",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="department",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="group",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="shift",
        ),
    ]
