# Generated by Django 5.1.7 on 2025-04-07 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0009_auto_20250407_1048"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planning",
            name="id_service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="rh.services"
            ),
        ),
    ]
