# Generated by Django 5.1.7 on 2025-05-13 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0009_remove_employee_card_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OvertimeValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "is_validated",
                    models.BooleanField(default=False, verbose_name="Validé"),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de validation"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overtime_validations",
                        to="rh.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Validation d'heures supplémentaires",
                "verbose_name_plural": "Validations d'heures supplémentaires",
                "unique_together": {("employee", "date")},
            },
        ),
    ]
