# Generated by Django 5.1.7 on 2025-04-07 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0010_alter_planning_id_service"),
    ]

    operations = []
