# Generated by Django 5.1.7 on 2025-05-14 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0010_overtimevalidation"),
    ]

    operations = [
        migrations.AddField(
            model_name="overtimevalidation",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="validated_par",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="validated_par",
                to="rh.personnel",
            ),
        ),
    ]
