# Generated by Django 5.1.7 on 2025-04-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0011_auto_20250407_1333"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="services",
            options={
                "managed": True,
                "permissions": [
                    ("view_service_comptabilité", "Peut voir le service comptabilité"),
                    (
                        "view_service_ressources_humaines",
                        "Peut voir le service ressources_humaines",
                    ),
                    ("view_service_direction", "Peut voir le service direction"),
                ],
            },
        ),
    ]
