# Generated by Django 5.1.7 on 2025-05-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0011_overtimevalidation_validated_by"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OvertimeValidation",
        ),
    ]
