# Generated by Django 5.1.7 on 2025-04-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0012_alter_services_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="services",
            options={"managed": True},
        ),
    ]
