# Generated by Django 5.1.7 on 2025-05-15 10:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0012_delete_overtimevalidation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSalaryConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cnas_employer_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=26.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Taux CNAS employeur (%)",
                    ),
                ),
                (
                    "cnas_employee_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=9.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Taux CNAS employé (%)",
                    ),
                ),
                (
                    "daily_meal_allowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=300.0,
                        max_digits=10,
                        verbose_name="Indemnité repas journalière (DZA)",
                    ),
                ),
                (
                    "daily_transport_allowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=200.0,
                        max_digits=10,
                        verbose_name="Indemnité transport journalière (DZA)",
                    ),
                ),
                ("update_date", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dernière modification par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration Salariale Globale",
                "verbose_name_plural": "Configuration Salariale Globale",
            },
        ),
        migrations.CreateModel(
            name="IRGBracket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant minimum"
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Montant maximum",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Taux d'imposition (%)",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="irg_brackets",
                        to="rh.globalsalaryconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tranche IRG",
                "verbose_name_plural": "Tranches IRG",
                "ordering": ["min_amount"],
            },
        ),
    ]
