# Generated by Django 5.1.7 on 2025-04-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0013_alter_services_options"),
    ]

    operations = []
