# Generated by Django 5.1.7 on 2025-05-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0013_globalsalaryconfig_irgbracket"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsalaryconfig",
            name="daily_absence_penalty",
            field=models.DecimalField(
                decimal_places=2,
                default=1500.0,
                max_digits=6,
                verbose_name="Pénalité absence journalière",
            ),
        ),
        migrations.AddField(
            model_name="globalsalaryconfig",
            name="late_minute_penalty",
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                max_digits=6,
                verbose_name="Pénalité par minute de retard",
            ),
        ),
        migrations.AddField(
            model_name="globalsalaryconfig",
            name="overtime_hourly_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=1.2,
                max_digits=6,
                verbose_name="Taux horaire heures supplémentaires",
            ),
        ),
    ]
