# Generated by Django 5.1.7 on 2025-04-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0014_create_missing_service_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personnel",
            options={"managed": True, "ordering": ["nom_prenom"]},
        ),
        migrations.RenameField(
            model_name="personnel",
            old_name="nom",
            new_name="nom_prenom",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="prenom",
        ),
    ]
