# Generated by Django 5.1.7 on 2025-05-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0014_globalsalaryconfig_daily_absence_penalty_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pointage",
            name="is_validated",
        ),
        migrations.AddField(
            model_name="pointage",
            name="ov_validated",
            field=models.BooleanField(default=False, verbose_name="Validé heur supp"),
        ),
        migrations.AlterField(
            model_name="globalsalaryconfig",
            name="daily_absence_penalty",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=6,
                verbose_name="Pénalité absence journalière",
            ),
        ),
        migrations.AlterField(
            model_name="globalsalaryconfig",
            name="late_minute_penalty",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=6,
                verbose_name="Pénalité par minute de retard",
            ),
        ),
    ]
