# Generated by Django 5.1.7 on 2025-05-16 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0015_remove_pointage_is_validated_pointage_ov_validated_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pointage",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Validé par",
            ),
        ),
        migrations.AddField(
            model_name="pointage",
            name="validation_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de validation"
            ),
        ),
    ]
