# Generated by Django 5.1.7 on 2025-05-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0016_pointage_validated_by_pointage_validation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsalaryconfig",
            name="holiday_hourly_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=1.2,
                max_digits=6,
                verbose_name="Taux horaire heures holiday",
            ),
        ),
    ]
