# Generated by Django 5.1.7 on 2025-04-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0017_employee_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="card_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="last_sync",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
