# Generated by Django 5.1.7 on 2025-04-10 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0018_employee_card_number_employee_last_sync"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="last_sync",
            new_name="last_updated",
        ),
        migrations.AddField(
            model_name="attendance",
            name="synced_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="employee",
            name="group",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="check_type",
            field=models.CharField(
                choices=[("IN", "Entrée"), ("OUT", "Sortie")], max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="anviz_id",
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("employee", "check_time")},
        ),
    ]
