# Generated by Django 5.1.7 on 2025-04-10 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0019_rename_last_sync_employee_last_updated_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"verbose_name": "Pointage", "verbose_name_plural": "Pointages"},
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "Employé", "verbose_name_plural": "Employés"},
        ),
        migrations.AlterField(
            model_name="attendance",
            name="check_time",
            field=models.DateTimeField(verbose_name="Heure de pointage"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="check_type",
            field=models.CharField(
                choices=[("IN", "Entrée"), ("OUT", "Sortie")],
                max_length=3,
                verbose_name="Type de pointage",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="rh.employee",
                verbose_name="Employé",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="synced_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de synchronisation"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="anviz_id",
            field=models.BigIntegerField(unique=True, verbose_name="ID Anviz"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="card_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Numéro de badge"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Département"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="group",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Groupe"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Dernière mise à jour"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nom complet"),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["check_time"], name="rh_attendan_check_t_0de09e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["employee", "check_time"], name="rh_attendan_employe_989d3f_idx"
            ),
        ),
    ]
