# Generated by Django 5.1.7 on 2025-04-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0020_alter_attendance_options_alter_employee_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_successful_sync", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
