# Generated by Django 5.1.7 on 2025-04-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0021_synchistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="check_type",
            field=models.CharField(
                choices=[
                    ("IN", "Entrée"),
                    ("OUT", "Sortie"),
                    ("2", "Pause départ"),
                    ("3", "Pause retour"),
                    ("4", "Heure supplémentaire"),
                    ("5", "Retard"),
                    ("6", "Absence"),
                ],
                max_length=6,
                verbose_name="Type de pointage",
            ),
        ),
    ]
