# Generated by Django 5.1.7 on 2025-04-10 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0022_alter_attendance_check_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SyncHistory",
        ),
    ]
