# Generated by Django 5.1.7 on 2025-04-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0023_delete_synchistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="shift",
            field=models.CharField(
                choices=[("day", "Jour"), ("night", "Nuit"), ("24h", "24h")],
                default="day",
                max_length=5,
                verbose_name="Type de shift",
            ),
        ),
    ]
