# Generated by Django 5.1.7 on 2025-04-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0024_employee_shift"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="reference_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="reference_start",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
