# Generated by Django 5.1.7 on 2025-04-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0025_employee_reference_end_employee_reference_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="check_type",
            field=models.CharField(
                choices=[
                    ("IN", "Entrée"),
                    ("OUT", "Sortie"),
                    ("2", "Début pause"),
                    ("3", "Fin pause"),
                    ("4", "Heure supplémentaire"),
                    ("5", "Retard"),
                    ("6", "Absence"),
                ],
                max_length=6,
                verbose_name="Type de pointage",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="reference_end",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Heure de fin de référence"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="reference_start",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Heure de début de référence"
            ),
        ),
    ]
