# Generated by Django 5.1.7 on 2025-04-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0026_alter_attendance_check_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnvizConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Nom"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        protocol="IPv4", verbose_name="Adresse IP"
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=100, verbose_name="Nom d'utilisateur"),
                ),
                (
                    "password",
                    models.CharField(max_length=100, verbose_name="Mot de passe"),
                ),
                (
                    "session_timeout",
                    models.PositiveIntegerField(
                        default=1800, verbose_name="Délai de session (secondes)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration Anviz",
                "verbose_name_plural": "Configurations Anviz",
            },
        ),
    ]
