# Generated by Django 5.1.7 on 2025-04-14 14:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0027_anvizconfiguration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anvizconfiguration",
            options={
                "verbose_name": "Configuration Pointeuse",
                "verbose_name_plural": "Configuration Pointeuse",
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("VAC", "Congé annuel"),
                            ("SIC", "Congé maladie"),
                            ("MAT", "Congé maternité"),
                            ("PAT", "Congé paternité"),
                            ("AUT", "Autre"),
                        ],
                        default="VAC",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PEN", "En attente"),
                            ("APP", "Approuvé"),
                            ("REJ", "Rejeté"),
                            ("CAN", "Annulé"),
                        ],
                        default="PEN",
                        max_length=3,
                    ),
                ),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="rh.personnel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OtherRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("EQU", "Demande de matériel"),
                            ("FOR", "Demande de formation"),
                            ("DOC", "Demande de document"),
                            ("AUT", "Autre demande"),
                        ],
                        default="AUT",
                        max_length=3,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PEN", "En attente"),
                            ("APP", "Approuvée"),
                            ("REJ", "Rejetée"),
                            ("CAN", "Annulée"),
                        ],
                        default="PEN",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("response", models.TextField(blank=True, null=True)),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_requests",
                        to="rh.personnel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalaryAdvanceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("request_date", models.DateField(default=django.utils.timezone.now)),
                ("payment_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PEN", "En attente"),
                            ("APP", "Approuvée"),
                            ("REJ", "Rejetée"),
                            ("CAN", "Annulée"),
                        ],
                        default="PEN",
                        max_length=3,
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_advances",
                        to="rh.personnel",
                    ),
                ),
            ],
        ),
    ]
