# Generated by Django 5.1.7 on 2025-04-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0028_alter_anvizconfiguration_options_leaverequest_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OtherRequest",
        ),
    ]
