# Generated by Django 5.1.7 on 2025-04-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0029_delete_otherrequest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaverequest",
            options={
                "permissions": [
                    ("process_leave_request", "Peut traiter les demandes de congé")
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="salaryadvancerequest",
            options={
                "permissions": [
                    (
                        "process_salaryadvance_request",
                        "Peut traiter les demandes d'avance sur salaire",
                    )
                ]
            },
        ),
    ]
