# Generated by Django 5.1.7 on 2025-04-15 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0030_alter_leaverequest_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PointagesActes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nbr_actes", models.IntegerField()),
                (
                    "id_acte",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_acte",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rh.honorairesacte",
                    ),
                ),
                (
                    "id_planning",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_planning",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rh.planning",
                    ),
                ),
            ],
            options={
                "db_table": "pointages_actes",
                "managed": True,
            },
        ),
    ]
